// AUTO-GENERATED by build workflow — do not edit by hand.
// Populated by `xxd -i Cousine-Regular.ttf > src/font_cousine.h` during CI.
// At dev time this file is a stub; the workflow overwrites it before compiling.
#pragma once
// stub — replaced by workflow
static const unsigned char cousine_ttf_data[] = { 0x00 };
static const unsigned int  cousine_ttf_size   = 0;
