// ============================================================
//  Sightline — Video Player UI
//  Dear ImGui + Win32 + Direct3D9
//  Single EXE, compatible Windows XP SP3 x86 -> Windows 11
//  Compiler: MinGW-w64 i686
// ============================================================

#define WINVER       0x0501
#define _WIN32_WINNT 0x0501
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d9.h>
// WIC — available since XP SP3, no extra lib beyond ole32/oleaut32
#include <wincodec.h>

#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx9.h"

// ── Embedded Electrolize font ───────────────────────────────
// font_electrolize.h is always present (stub or real).
// CI overwrites it with real TTF bytes before compiling.
#include "font_electrolize.h"
// Use font if len > 4 (real data, not the stub {0})
#define HAS_ELECTROLIZE_EMBED (electrolize_regular_ttf_len > 4)

// ── Embedded logo PNG ───────────────────────────────────────
// logo_data.h is generated by CI from src/Sightline Logo.png
#if __has_include("logo_data.h")
  #include "logo_data.h"
  #define HAS_LOGO_EMBED (sightline_logo_png_len > 4)
#else
  static const unsigned char sightline_logo_png[]   = {0};
  static const unsigned int  sightline_logo_png_len = 0;
  #define HAS_LOGO_EMBED 0
#endif

#include <cstdio>
#include <cmath>
#include <cstring>
#include <string>

// ─── colour palette ──────────────────────────────────────────
#define COL32(r,g,b,a) IM_COL32(r,g,b,a)
static const ImU32 C_BG          = COL32(0x0C,0x10,0x14,255);
static const ImU32 C_SURFACE     = COL32(0x13,0x19,0x20,255);
static const ImU32 C_SURFACE2    = COL32(0x19,0x20,0x28,255);
static const ImU32 C_SURFACE3    = COL32(0x1E,0x26,0x2F,255);
static const ImU32 C_DIVIDER     = COL32(0x1B,0x22,0x29,255);
static const ImU32 C_BORDER      = COL32(255,255,255,18);
static const ImU32 C_BORDER_STR  = COL32(255,255,255,31);
static const ImU32 C_TEXT        = COL32(0xE6,0xED,0xF2,255);
static const ImU32 C_TEXT_MUTED  = COL32(0x8A,0x97,0xA3,255);
static const ImU32 C_TEXT_FAINT  = COL32(0x4D,0x5E,0x69,255);
static const ImU32 C_ACCENT      = COL32(0x4E,0xA8,0xA8,255);
static const ImU32 C_ACCENT_HOV  = COL32(0x62,0xBC,0xBC,255);
static const ImU32 C_ACCENT_SOFT = COL32(78,168,168,31);
static const ImU32 C_ACCENT_LINE = COL32(78,168,168,89);
static const ImU32 C_SUCCESS     = COL32(0x6B,0xAA,0x78,255);
static const ImU32 C_ERROR       = COL32(0xC9,0x6B,0x6B,255);
static const ImU32 C_BLACK       = COL32(0,0,0,255);
static const ImU32 C_WHITE       = COL32(0xFF,0xFF,0xFF,255);

static inline ImVec4 U32toV4(ImU32 c){
    return ImVec4(((c>>0)&0xFF)/255.f,((c>>8)&0xFF)/255.f,
                  ((c>>16)&0xFF)/255.f,((c>>24)&0xFF)/255.f);
}

// ─── glyph ranges ────────────────────────────────────────────
static const ImWchar g_glyph_ranges[] = {
    0x0020,0x00FF, 0x0100,0x024F, 0x2000,0x206F, 0x20AC,0x20AC, 0,
};

// ─── font handles ────────────────────────────────────────────
static ImFont* g_font13 = nullptr;
static ImFont* g_font16 = nullptr;

// ─── logo DX9 texture ────────────────────────────────────────
static LPDIRECT3DTEXTURE9 g_logoTex    = NULL;
static int                g_logoTexW   = 0;
static int                g_logoTexH   = 0;

// ─── app state ───────────────────────────────────────────────
static float  g_seek       = 0.175f;
static float  g_vol        = 0.80f;
static bool   g_playing    = true;
static int    g_tab        = 0;
static int    g_quality    = 0;
static bool   g_subscribed = false;
static char   g_search[128]= "rickroll";
static float  g_sideScroll = 0.f;

static const char* g_qualityOpts[] = {"2160p","1080p","720p","480p"};
static const int   g_qualityCount  = 4;

struct RelItem { const char* title; const char* channel; const char* views; const char* dur; ImU32 grad; };
static const RelItem g_related[] = {
    {"Rick Astley \xe2\x80\x94 Never Gonna Give You Up (Official Video) 4K Remaster","Rick Astley","1.7B views","3:33",COL32(0x13,0x19,0x20,255)},
    {"Best of 80s Music Legends \xe2\x80\x94 Team Formidable Mix","Radio 80s Hits","2.1M views","42:18",COL32(0x1a,0x20,0x30,255)},
    {"Rick Astley \xe2\x80\x94 Mix de Exitos Completo","Nanojams300","890K views","31:08",COL32(0x1a,0x28,0x20,255)},
    {"Daft Punk ft. Pharrell Williams \xe2\x80\x94 Get Lucky (Official)","pftpremials","1.4B views","3:44",COL32(0x20,0x18,0x28,255)},
    {"Shakira, Burna Boy \xe2\x80\x94 Dai Dai (Official Video)","shakiriaVEVO","420M views","3:59",COL32(0x28,0x18,0x20,255)},
    {"Phil Collins, Rod Stewart \xe2\x80\x94 Soulful 80s Mix","Soft Rock Soulful","3.2M views","4:07",COL32(0x18,0x20,0x28,255)},
    {"George Michael \xe2\x80\x94 Careless Whisper (Official 4K)","georgemc.feel","1.1B views","5:11",COL32(0x28,0x20,0x18,255)},
    {"Ultimate 80s Classics: Timeless Icons Mix","Flashback Grooves","5.7M views","58:01",COL32(0x18,0x18,0x28,255)},
    {"Eagles \xe2\x80\x94 Hotel California (Live 1977 Official)","Eagles","987M views","8:45",COL32(0x20,0x18,0x20,255)},
};
static const int g_relatedCount = 9;

// ─── D3D9 globals ────────────────────────────────────────────
static LPDIRECT3D9           g_pD3D    = NULL;
static LPDIRECT3DDEVICE9     g_pd3dDev = NULL;
static D3DPRESENT_PARAMETERS g_d3dpp   = {};
static HWND                  g_hwnd    = NULL;

static bool CreateDeviceD3D(HWND hWnd)
{
    if((g_pD3D = Direct3DCreate9(D3D_SDK_VERSION)) == NULL) return false;
    ZeroMemory(&g_d3dpp,sizeof(g_d3dpp));
    g_d3dpp.Windowed               = TRUE;
    g_d3dpp.SwapEffect             = D3DSWAPEFFECT_DISCARD;
    g_d3dpp.BackBufferFormat       = D3DFMT_UNKNOWN;
    g_d3dpp.EnableAutoDepthStencil = TRUE;
    g_d3dpp.AutoDepthStencilFormat = D3DFMT_D16;
    g_d3dpp.PresentationInterval   = D3DPRESENT_INTERVAL_ONE;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_HARDWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_SOFTWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    return false;
}
static void CleanupDevice()
{
    if(g_logoTex){ g_logoTex->Release(); g_logoTex=NULL; }
    if(g_pd3dDev){ g_pd3dDev->Release(); g_pd3dDev=NULL; }
    if(g_pD3D)   { g_pD3D->Release();    g_pD3D=NULL; }
}
static void ResetDevice()
{
    ImGui_ImplDX9_InvalidateDeviceObjects();
    g_pd3dDev->Reset(&g_d3dpp);
    ImGui_ImplDX9_CreateDeviceObjects();
}

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND,UINT,WPARAM,LPARAM);
static LRESULT WINAPI WndProc(HWND hWnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
    if(ImGui_ImplWin32_WndProcHandler(hWnd,msg,wParam,lParam)) return true;
    switch(msg){
        case WM_SIZE:
            if(g_pd3dDev && wParam!=SIZE_MINIMIZED){
                g_d3dpp.BackBufferWidth  = LOWORD(lParam);
                g_d3dpp.BackBufferHeight = HIWORD(lParam);
                ResetDevice();
            }
            return 0;
        case WM_DESTROY: PostQuitMessage(0); return 0;
    }
    return DefWindowProcA(hWnd,msg,wParam,lParam);
}

// ─── WIC PNG loader → DX9 texture ────────────────────────────
static bool LoadPNGFromMemory(const unsigned char* data, unsigned int len,
                               LPDIRECT3DDEVICE9 dev,
                               LPDIRECT3DTEXTURE9* outTex, int* outW, int* outH)
{
    if(!data || len==0 || !dev || !outTex || !outW || !outH) return false;

    IWICImagingFactory*    wicFactory = NULL;
    IWICStream*            wicStream  = NULL;
    IWICBitmapDecoder*     decoder    = NULL;
    IWICBitmapFrameDecode* frame      = NULL;
    IWICFormatConverter*   converter  = NULL;
    bool ok = false;

    if(FAILED(CoCreateInstance(CLSID_WICImagingFactory, NULL,
        CLSCTX_INPROC_SERVER, IID_IWICImagingFactory,
        (void**)&wicFactory))) goto cleanup;

    if(FAILED(wicFactory->CreateStream(&wicStream))) goto cleanup;
    if(FAILED(wicStream->InitializeFromMemory(
        const_cast<BYTE*>(data), len))) goto cleanup;
    if(FAILED(wicFactory->CreateDecoderFromStream(
        wicStream, NULL,
        WICDecodeMetadataCacheOnLoad, &decoder))) goto cleanup;
    if(FAILED(decoder->GetFrame(0, &frame))) goto cleanup;

    {
        UINT w=0, h=0;
        if(FAILED(frame->GetSize(&w, &h))) goto cleanup;

        if(FAILED(wicFactory->CreateFormatConverter(&converter))) goto cleanup;
        if(FAILED(converter->Initialize(
            frame,
            GUID_WICPixelFormat32bppBGRA,
            WICBitmapDitherTypeNone, NULL, 0.0,
            WICBitmapPaletteTypeCustom))) goto cleanup;

        LPDIRECT3DTEXTURE9 tex = NULL;
        if(FAILED(dev->CreateTexture(w, h, 1, 0, D3DFMT_A8R8G8B8,
            D3DPOOL_MANAGED, &tex, NULL))) goto cleanup;

        D3DLOCKED_RECT lr;
        if(FAILED(tex->LockRect(0, &lr, NULL, 0))){
            tex->Release(); goto cleanup;
        }
        UINT stride = w * 4;
        converter->CopyPixels(NULL, stride, h * stride, (BYTE*)lr.pBits);
        tex->UnlockRect(0);

        *outTex = tex;
        *outW   = (int)w;
        *outH   = (int)h;
        ok = true;
    }

cleanup:
    if(converter)  converter->Release();
    if(frame)      frame->Release();
    if(decoder)    decoder->Release();
    if(wicStream)  wicStream->Release();
    if(wicFactory) wicFactory->Release();
    return ok;
}

// ─── helpers ─────────────────────────────────────────────────
static void RectFill(ImDrawList* dl,ImVec2 p,ImVec2 sz,ImU32 c,float r=0.f)
{ dl->AddRectFilled(p,{p.x+sz.x,p.y+sz.y},c,r); }
static void Rect(ImDrawList* dl,ImVec2 p,ImVec2 sz,ImU32 c,float r=0.f,float t=1.f)
{ dl->AddRect(p,{p.x+sz.x,p.y+sz.y},c,r,0,t); }

static void Txt(ImDrawList* dl,ImVec2 p,ImU32 c,const char* s,float wrap=0.f)
{
    if(!g_font13) return;
    if(wrap>0.f) dl->AddText(g_font13,13.f,p,c,s,NULL,wrap);
    else         dl->AddText(g_font13,13.f,p,c,s);
}
static void Txt16(ImDrawList* dl,ImVec2 p,ImU32 c,const char* s,float wrap=0.f)
{
    ImFont* f  = (g_font16 && g_font16!=g_font13) ? g_font16 : g_font13;
    float   sz = (g_font16 && g_font16!=g_font13) ? 16.f : 13.f;
    if(!f) return;
    if(wrap>0.f) dl->AddText(f,sz,p,c,s,NULL,wrap);
    else         d