// ============================================================
//  Sightline — Video Player UI
//  Dear ImGui + Win32 + Direct3D9
//  Single EXE, compatible Windows XP SP3 x86 -> Windows 11
//  Compiler: MinGW-w64 i686
// ============================================================

#define WINVER       0x0501
#define _WIN32_WINNT 0x0501
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <d3d9.h>
// WIC GUIDs are resolved via libuuid.a at link time (-luuid).
// Do NOT use #define INITGUID here — it does not work for WIC
// GUIDs with mingw-w64; -luuid in the link step is the fix.
#include <wincodec.h>

#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx9.h"

// ── Embedded Electrolize font ─────────────────────────────────
// font_electrolize.h is always present (stub or real).
// CI overwrites it with real TTF bytes before compiling.
// IMPORTANT: HAS_ELECTROLIZE_EMBED must be a plain 0/1 integer
// constant so that #if works at preprocessor time.
// The stub commits len=0 so we define the macro to 0 here;
// the CI regenerates this file with len>0 before building.
#include "font_electrolize.h"
// Runtime check — DO NOT use #if here; use a regular if() below.
static inline bool HasElectrolize() { return electrolize_regular_ttf_len > 4; }

// ── Embedded logo PNG ─────────────────────────────────────────
// logo_data.h is generated by CI from src/Sightline Logo.png
#if __has_include("logo_data.h")
  #include "logo_data.h"
  static inline bool HasLogo() { return sightline_logo_png_len > 4; }
#else
  static const unsigned char sightline_logo_png[]   = {0};
  static const unsigned int  sightline_logo_png_len = 0;
  static inline bool HasLogo() { return false; }
#endif

#include <cstdio>
#include <cmath>
#include <cstring>
#include <string>

// ─── colour palette ──────────────────────────────────────────
#define COL32(r,g,b,a) IM_COL32(r,g,b,a)
static const ImU32 C_BG          = COL32(0x0C,0x10,0x14,255);
static const ImU32 C_SURFACE     = COL32(0x13,0x19,0x20,255);
static const ImU32 C_SURFACE2    = COL32(0x19,0x20,0x28,255);
static const ImU32 C_SURFACE3    = COL32(0x1E,0x26,0x2F,255);
static const ImU32 C_DIVIDER     = COL32(0x1B,0x22,0x29,255);
static const ImU32 C_BORDER      = COL32(255,255,255,18);
static const ImU32 C_BORDER_STR  = COL32(255,255,255,31);
static const ImU32 C_TEXT        = COL32(0xE6,0xED,0xF2,255);
static const ImU32 C_TEXT_MUTED  = COL32(0x8A,0x97,0xA3,255);
static const ImU32 C_TEXT_FAINT  = COL32(0x4D,0x5E,0x69,255);
static const ImU32 C_ACCENT      = COL32(0x4E,0xA8,0xA8,255);
static const ImU32 C_ACCENT_HOV  = COL32(0x62,0xBC,0xBC,255);
static const ImU32 C_ACCENT_SOFT = COL32(78,168,168,31);
static const ImU32 C_ACCENT_LINE = COL32(78,168,168,89);
static const ImU32 C_SUCCESS     = COL32(0x6B,0xAA,0x78,255);
static const ImU32 C_ERROR       = COL32(0xC9,0x6B,0x6B,255);
static const ImU32 C_BLACK       = COL32(0,0,0,255);
static const ImU32 C_WHITE       = COL32(0xFF,0xFF,0xFF,255);

static inline ImVec4 U32toV4(ImU32 c){
    return ImVec4(((c>>0)&0xFF)/255.f,((c>>8)&0xFF)/255.f,
                  ((c>>16)&0xFF)/255.f,((c>>24)&0xFF)/255.f);
}

// ─── glyph ranges ────────────────────────────────────────────
static const ImWchar g_glyph_ranges[] = {
    0x0020,0x00FF, 0x0100,0x024F, 0x2000,0x206F, 0x20AC,0x20AC, 0,
};

// ─── font handles ────────────────────────────────────────────
static ImFont* g_font13 = nullptr;
static ImFont* g_font16 = nullptr;

// ─── logo DX9 texture ────────────────────────────────────────
static LPDIRECT3DTEXTURE9 g_logoTex    = NULL;
static int                g_logoTexW   = 0;
static int                g_logoTexH   = 0;

// ─── app state ───────────────────────────────────────────────
static float  g_seek       = 0.175f;
static float  g_vol        = 0.80f;
static bool   g_playing    = true;
static int    g_tab        = 0;
static int    g_quality    = 0;
static bool   g_subscribed = false;
static char   g_search[128]= "rickroll";
static float  g_sideScroll = 0.f;

static const char* g_qualityOpts[] = {"2160p","1080p","720p","480p"};
static const int   g_qualityCount  = 4;

struct RelItem { const char* title; const char* channel; const char* views; const char* dur; ImU32 grad; };
static const RelItem g_related[] = {
    {"Rick Astley \xe2\x80\x94 Never Gonna Give You Up (Official Video) 4K Remaster","Rick Astley","1.7B views","3:33",COL32(0x13,0x19,0x20,255)},
    {"Best of 80s Music Legends \xe2\x80\x94 Team Formidable Mix","Radio 80s Hits","2.1M views","42:18",COL32(0x1a,0x20,0x30,255)},
    {"Rick Astley \xe2\x80\x94 Mix de Exitos Completo","Nanojams300","890K views","31:08",COL32(0x1a,0x28,0x20,255)},
    {"Daft Punk ft. Pharrell Williams \xe2\x80\x94 Get Lucky (Official)","pftpremials","1.4B views","3:44",COL32(0x20,0x18,0x28,255)},
    {"Shakira, Burna Boy \xe2\x80\x94 Dai Dai (Official Video)","shakiriaVEVO","420M views","3:59",COL32(0x28,0x18,0x20,255)},
    {"Phil Collins, Rod Stewart \xe2\x80\x94 Soulful 80s Mix","Soft Rock Soulful","3.2M views","4:07",COL32(0x18,0x20,0x28,255)},
    {"George Michael \xe2\x80\x94 Careless Whisper (Official 4K)","georgemc.feel","1.1B views","5:11",COL32(0x28,0x20,0x18,255)},
    {"Ultimate 80s Classics: Timeless Icons Mix","Flashback Grooves","5.7M views","58:01",COL32(0x18,0x18,0x28,255)},
    {"Eagles \xe2\x80\x94 Hotel California (Live 1977 Official)","Eagles","987M views","8:45",COL32(0x20,0x18,0x20,255)},
};
static const int g_relatedCount = 9;

// ─── D3D9 globals ────────────────────────────────────────────
static LPDIRECT3D9           g_pD3D    = NULL;
static LPDIRECT3DDEVICE9     g_pd3dDev = NULL;
static D3DPRESENT_PARAMETERS g_d3dpp   = {};
static HWND                  g_hwnd    = NULL;

static bool CreateDeviceD3D(HWND hWnd)
{
    if((g_pD3D = Direct3DCreate9(D3D_SDK_VERSION)) == NULL) return false;
    ZeroMemory(&g_d3dpp,sizeof(g_d3dpp));
    g_d3dpp.Windowed               = TRUE;
    g_d3dpp.SwapEffect             = D3DSWAPEFFECT_DISCARD;
    g_d3dpp.BackBufferFormat       = D3DFMT_UNKNOWN;
    g_d3dpp.EnableAutoDepthStencil = TRUE;
    g_d3dpp.AutoDepthStencilFormat = D3DFMT_D16;
    g_d3dpp.PresentationInterval   = D3DPRESENT_INTERVAL_ONE;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_HARDWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_SOFTWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    return false;
}
static void CleanupDevice()
{
    if(g_logoTex){ g_logoTex->Release(); g_logoTex=NULL; }
    if(g_pd3dDev){ g_pd3dDev->Release(); g_pd3dDev=NULL; }
    if(g_pD3D)   { g_pD3D->Release();    g_pD3D=NULL; }
}
static void ResetDevice()
{
    ImGui_ImplDX9_InvalidateDeviceObjects();
    g_pd3dDev->Reset(&g_d3dpp);
    ImGui_ImplDX9_CreateDeviceObjects();
}

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND,UINT,WPARAM,LPARAM);
static LRESULT WINAPI WndProc(HWND hWnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
    if(ImGui_ImplWin32_WndProcHandler(hWnd,msg,wParam,lParam)) return true;
    switch(msg){
        case WM_SIZE:
            if(g_pd3dDev && wParam!=SIZE_MINIMIZED){
                g_d3dpp.BackBufferWidth  = LOWORD(lParam);
                g_d3dpp.BackBufferHeight = HIWORD(lParam);
                ResetDevice();
            }
            return 0;
        case WM_DESTROY: PostQuitMessage(0); return 0;
    }
    return DefWindowProcA(hWnd,msg,wParam,lParam);
}

// ─── WIC PNG loader → DX9 texture ────────────────────────────
// Uses Windows Imaging Component (XP SP3+). No GDI+, no extra libs.
static bool LoadPNGFromMemory(const unsigned char* data, unsigned int len,
                               LPDIRECT3DDEVICE9 dev,
                               LPDIRECT3DTEXTURE9* outTex, int* outW, int* outH)
{
    if(!data || len==0 || !dev || !outTex || !outW || !outH) return false;

    IWICImagingFactory*    wicFactory = NULL;
    IWICStream*            wicStream  = NULL;
    IWICBitmapDecoder*     decoder    = NULL;
    IWICBitmapFrameDecode* frame      = NULL;
    IWICFormatConverter*   converter  = NULL;
    bool ok = false;

    if(FAILED(CoCreateInstance(CLSID_WICImagingFactory, NULL,
        CLSCTX_INPROC_SERVER, IID_IWICImagingFactory,
        (void**)&wicFactory))) goto cleanup;

    if(FAILED(wicFactory->CreateStream(&wicStream))) goto cleanup;
    if(FAILED(wicStream->InitializeFromMemory(
        const_cast<BYTE*>(data), len))) goto cleanup;
    if(FAILED(wicFactory->CreateDecoderFromStream(
        wicStream, NULL,
        WICDecodeMetadataCacheOnLoad, &decoder))) goto cleanup;
    if(FAILED(decoder->GetFrame(0, &frame))) goto cleanup;

    {
        UINT w=0, h=0;
        if(FAILED(frame->GetSize(&w, &h))) goto cleanup;

        if(FAILED(wicFactory->CreateFormatConverter(&converter))) goto cleanup;
        if(FAILED(converter->Initialize(
            frame,
            GUID_WICPixelFormat32bppBGRA,
            WICBitmapDitherTypeNone, NULL, 0.0,
            WICBitmapPaletteTypeCustom))) goto cleanup;

        LPDIRECT3DTEXTURE9 tex = NULL;
        if(FAILED(dev->CreateTexture(w, h, 1, 0, D3DFMT_A8R8G8B8,
            D3DPOOL_MANAGED, &tex, NULL))) goto cleanup;

        D3DLOCKED_RECT lr;
        if(FAILED(tex->LockRect(0, &lr, NULL, 0))){
            tex->Release(); goto cleanup;
        }
        UINT stride = w * 4;
        converter->CopyPixels(NULL, stride, h * stride, (BYTE*)lr.pBits);
        tex->UnlockRect(0);

        *outTex = tex;
        *outW   = (int)w;
        *outH   = (int)h;
        ok = true;
    }

cleanup:
    if(converter)  converter->Release();
    if(frame)      frame->Release();
    if(decoder)    decoder->Release();
    if(wicStream)  wicStream->Release();
    if(wicFactory) wicFactory->Release();
    return ok;
}

// ─── helpers ─────────────────────────────────────────────────
static void RectFill(ImDrawList* dl,ImVec2 p,ImVec2 sz,ImU32 c,float r=0.f)
{ dl->AddRectFilled(p,{p.x+sz.x,p.y+sz.y},c,r); }
static void Rect(ImDrawList* dl,ImVec2 p,ImVec2 sz,ImU32 c,float r=0.f,float t=1.f)
{ dl->AddRect(p,{p.x+sz.x,p.y+sz.y},c,r,0,t); }

static void Txt(ImDrawList* dl,ImVec2 p,ImU32 c,const char* s,float wrap=0.f)
{
    if(!g_font13) return;
    if(wrap>0.f) dl->AddText(g_font13,13.f,p,c,s,NULL,wrap);
    else         dl->AddText(g_font13,13.f,p,c,s);
}
static void Txt16(ImDrawList* dl,ImVec2 p,ImU32 c,const char* s,float wrap=0.f)
{
    ImFont* f  = (g_font16 && g_font16!=g_font13) ? g_font16 : g_font13;
    float   sz = (g_font16 && g_font16!=g_font13) ? 16.f : 13.f;
    if(!f) return;
    if(wrap>0.f) dl->AddText(f,sz,p,c,s,NULL,wrap);
    else         dl->AddText(f,sz,p,c,s);
}
static ImVec2 TS(const char* s,float wrap=0.f)
{
    if(!g_font13) return ImGui::CalcTextSize(s);
    return g_font13->CalcTextSizeA(13.f,FLT_MAX,wrap,s);
}
static ImVec2 TS16(const char* s,float wrap=0.f)
{
    ImFont* f  = (g_font16 && g_font16!=g_font13) ? g_font16 : g_font13;
    float   sz = (g_font16 && g_font16!=g_font13) ? 16.f : 13.f;
    if(!f) return ImGui::CalcTextSize(s);
    return f->CalcTextSizeA(sz,FLT_MAX,wrap,s);
}

// ─── icon drawing ────────────────────────────────────────────
static void IconPlay(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{ dl->AddTriangleFilled({c.x-r*.4f,c.y-r*.6f},{c.x+r*.7f,c.y},{c.x-r*.4f,c.y+r*.6f},col); }

static void IconPause(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float w=r*.28f,h=r*.65f,g=r*.22f;
    dl->AddRectFilled({c.x-g-w,c.y-h},{c.x-g,c.y+h},col,1.f);
    dl->AddRectFilled({c.x+g,c.y-h},{c.x+g+w,c.y+h},col,1.f);
}
static void IconVolume(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hh=r*.5f;
    dl->AddRectFilled({c.x-r*.5f,c.y-hh*.55f},{c.x-r*.1f,c.y+hh*.55f},col);
    dl->PathLineTo({c.x-r*.12f,c.y-hh});
    dl->PathLineTo({c.x+r*.45f,c.y-hh*.5f});
    dl->PathLineTo({c.x+r*.45f,c.y+hh*.5f});
    dl->PathLineTo({c.x-r*.12f,c.y+hh});
    dl->PathFillConvex(col);
    dl->PathArcTo({c.x+r*.15f,c.y},r*.55f,-3.14f*.4f,3.14f*.4f,8);
    dl->PathStroke(col,false,1.2f);
}
static void IconFullscreen(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float s=r*.6f,d=r*.25f;
    float lx=c.x-s,rx=c.x+s,ty=c.y-s,by=c.y+s;
    dl->AddLine({lx,ty},{lx+d,ty},col,1.3f); dl->AddLine({lx,ty},{lx,ty+d},col,1.3f);
    dl->AddLine({rx,ty},{rx-d,ty},col,1.3f); dl->AddLine({rx,ty},{rx,ty+d},col,1.3f);
    dl->AddLine({lx,by},{lx+d,by},col,1.3f); dl->AddLine({lx,by},{lx,by-d},col,1.3f);
    dl->AddLine({rx,by},{rx-d,by},col,1.3f); dl->AddLine({rx,by},{rx,by-d},col,1.3f);
}
static void IconShare(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    dl->AddCircle({c.x+r*.6f,c.y-r*.55f},r*.22f,col,0,1.3f);
    dl->AddCircle({c.x+r*.6f,c.y+r*.55f},r*.22f,col,0,1.3f);
    dl->AddCircle({c.x-r*.6f,c.y},r*.22f,col,0,1.3f);
    dl->AddLine({c.x-r*.4f,c.y},{c.x+r*.4f,c.y-r*.5f},col,1.3f);
    dl->AddLine({c.x-r*.4f,c.y},{c.x+r*.4f,c.y+r*.5f},col,1.3f);
}
static void IconDownload(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.32f;
    dl->AddLine({c.x,c.y-r*.6f},{c.x,c.y+r*.05f},col,1.4f);
    dl->AddLine({c.x,c.y+r*.05f},{c.x-hw,c.y-r*.2f},col,1.4f);
    dl->AddLine({c.x,c.y+r*.05f},{c.x+hw,c.y-r*.2f},col,1.4f);
    dl->AddLine({c.x-r*.55f,c.y+r*.5f},{c.x+r*.55f,c.y+r*.5f},col,1.4f);
}
static void IconDots(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float rr=r*.18f;
    dl->AddCircleFilled({c.x-r*.6f,c.y},rr,col);
    dl->AddCircleFilled(c,rr,col);
    dl->AddCircleFilled({c.x+r*.6f,c.y},rr,col);
}
static void IconThumbUp(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.45f,hh=r*.55f;
    ImVec2 pts[6]={{c.x-hw,c.y+hh},{c.x-hw,c.y},{c.x-hw*.2f,c.y-hh*.1f},
                   {c.x+hw*.3f,c.y-hh},{c.x+hw,c.y-hh*.3f},{c.x+hw,c.y+hh}};
    for(int i=0;i<6;i++) dl->PathLineTo(pts[i]);
    dl->PathStroke(col,true,1.3f);
    dl->AddRectFilled({c.x-hw,c.y+hh*.1f},{c.x-hw+r*.22f,c.y+hh},col,1.f);
}
static void IconThumbDown(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.45f,hh=r*.55f;
    ImVec2 pts[6]={{c.x-hw,c.y-hh},{c.x-hw,c.y},{c.x-hw*.2f,c.y+hh*.1f},
                   {c.x+hw*.3f,c.y+hh},{c.x+hw,c.y+hh*.3f},{c.x+hw,c.y-hh}};
    for(int i=0;i<6;i++) dl->PathLineTo(pts[i]);
    dl->PathStroke(col,true,1.3f);
    dl->AddRectFilled({c.x-hw,c.y-hh},{c.x-hw+r*.22f,c.y-hh*.1f},col,1.f);
}

// FIX: arc radius reduced 0.65->0.45 so it doesn't crowd the
// '10' label.  Label is now placed 6px below icon centre (was
// centred on icon centre, causing arc/text overlap).
// Button callers were also widened to 30px (see DrawControls).
static void IconSkip(ImDrawList* dl,ImVec2 c,float r,ImU32 col,bool forward)
{
    if(forward){
        dl->PathArcTo(c,r*.45f,3.14f*0.3f,3.14f*2.3f,14);
    } else {
        dl->PathArcTo(c,r*.45f,3.14f*2.7f,3.14f*0.7f+3.14f*2.f,14);
    }
    dl->PathStroke(col,false,1.4f);
    float ang = forward ? (3.14f*2.3f) : (3.14f*2.7f);
    float ax = c.x + r*.45f * cosf(ang);
    float ay = c.y + r*.45f * sinf(ang);
    float as2 = r*.22f;
    ImVec2 tip={ax,ay};
    ImVec2 p1={ax+as2*cosf(ang+3.14f*0.7f),ay+as2*sinf(ang+3.14f*0.7f)};
    ImVec2 p2={ax+as2*cosf(ang-3.14f*0.7f),ay+as2*sinf(ang-3.14f*0.7f)};
    dl->AddTriangleFilled(tip,p1,p2,col);
    // Label placed below arc centre so it clears the stroke
    const char* num="10";
    ImVec2 ns=TS(num);
    dl->AddText(g_font13,13.f,{c.x-ns.x*.5f, c.y+r*.45f+3.f},col,num);
}

// ─── seekbar / volbar ─────────────────────────────────────────
// FIX: SeekBar and VolBar receive the caller's draw list (dl).
// FIX: SeekBar adds 6px horizontal padding so the thumb circle
//      at the extreme ends is never clipped by the bar edges.
//      The InvisibleButton still covers the full width so the
//      hit area is unaffected; value clamping uses the padded
//      rail extents.
static bool SeekBar(ImDrawList* dl,ImVec2 pos,float width,float height,
                    float* val,float buf,ImU32 cRail,ImU32 cBuf,ImU32 cFill,ImU32 cThumb)
{
    // Register hit area over the full bar width (no padding needed for input)
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton("##seek",{width,height});
    bool hov=ImGui::IsItemHovered();
    bool act=ImGui::IsItemActive();
    bool changed=false;

    // Padded rail: 6px inset on each side so the thumb is never clipped
    const float padX = 6.f;
    const float railX0 = pos.x + padX;
    const float railW  = width - padX * 2.f;

    if(act){
        float mx=ImGui::GetIO().MousePos.x;
        *val=(mx - railX0) / railW;
        if(*val<0.f)*val=0.f; if(*val>1.f)*val=1.f;
        changed=true;
    }
    float cy  = pos.y + height * .5f;
    float rh  = (hov||act) ? 5.f : 3.f;
    float ry  = cy - rh * .5f;
    // Draw rail, buffer fill, and value fill within padded bounds
    dl->AddRectFilled({railX0,ry},{railX0+railW,      ry+rh},cRail,rh*.5f);
    dl->AddRectFilled({railX0,ry},{railX0+railW*buf,  ry+rh},cBuf, rh*.5f);
    dl->AddRectFilled({railX0,ry},{railX0+railW*(*val),ry+rh},cFill,rh*.5f);
    if(hov||act){
        float tx = railX0 + railW * (*val);
        dl->AddCircleFilled({tx,cy},5.5f,cThumb);
    }
    return changed;
}

static bool VolBar(ImDrawList* dl,ImVec2 pos,float width,float height,float* val)
{
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton("##vol",{width,height});
    bool act=ImGui::IsItemActive();
    bool hov=ImGui::IsItemHovered();
    bool changed=false;
    if(act){
        float mx=ImGui::GetIO().MousePos.x;
        *val=(mx-pos.x)/width;
        if(*val<0.f)*val=0.f; if(*val>1.f)*val=1.f;
        changed=true;
    }
    float cy=pos.y+height*.5f;
    float rh=3.f,ry=cy-rh*.5f;
    dl->AddRectFilled({pos.x,ry},{pos.x+width,ry+rh},C_SURFACE3,rh*.5f);
    dl->AddRectFilled({pos.x,ry},{pos.x+width*(*val),ry+rh},C_ACCENT,rh*.5f);
    if(hov||act){
        float tx=pos.x+width*(*val);
        dl->AddCircleFilled({tx,cy},5.f,C_TEXT);
    }
    return changed;
}

// ─── IconBtn ─────────────────────────────────────────────────
static bool IconBtn(const char* id,ImVec2 pos,float size)
{
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton(id,{size,size});
    if(ImGui::IsItemHovered()){
        ImGui::GetWindowDrawList()->AddRectFilled(
            pos,{pos.x+size,pos.y+size},COL32(255,255,255,20),4.f);
    }
    return ImGui::IsItemActivated();
}

static bool TabBtn(ImDrawList* dl,const char* label,ImVec2 pos,bool active)
{
    ImVec2 ts=TS(label);
    float padX=12.f,h=26.f,w=ts.x+padX*2;
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton(label,{w,h});
    bool hov=ImGui::IsItemHovered();
    if(active){
        dl->AddRectFilled(pos,{pos.x+w,pos.y+h},C_ACCENT,5.f);
        dl->AddRect(pos,{pos.x+w,pos.y+h},C_ACCENT,5.f,0,1.f);
        Txt(dl,{pos.x+padX,pos.y+(h-ts.y)*.5f},C_WHITE,label);
    } else {
        ImU32 bg=hov?C_SURFACE3:C_SURFACE2;
        dl->AddRectFilled(pos,{pos.x+w,pos.y+h},bg,5.f);
        dl->AddRect(pos,{pos.x+w,pos.y+h},C_BORDER,5.f,0,1.f);
        Txt(dl,{pos.x+padX,pos.y+(h-ts.y)*.5f},hov?C_TEXT:C_TEXT_MUTED,label);
    }
    return ImGui::IsItemActivated();
}

// ─── logo drawing ────────────────────────────────────────────
// FIX: logoAreaH is now (h - 2) for a taller display area.
// FIX: scale base uses min(availH, texH) so a PNG whose native
//      height is already smaller than availH is not upscaled
//      beyond its natural size (avoids blurry up-scaling on XP).
//      dstW cap raised to 140px.
static void DrawLogoArea(ImDrawList* dl, ImVec2 pos, float availH)
{
    if(g_logoTex && g_logoTexW > 0 && g_logoTexH > 0){
        // Use the smaller of availH and the texture's native height as
        // the scaling reference so we never upscale a small logo.
        float scaleBase = (availH < (float)g_logoTexH) ? availH : (float)g_logoTexH;
        float scale = scaleBase / (float)g_logoTexH;
        float dstW  = (float)g_logoTexW * scale;
        // Cap width so a wide PNG never overflows into nav buttons
        if(dstW > 140.f){ scale = 140.f / (float)g_logoTexW; dstW = 140.f; }
        float dstH  = (float)g_logoTexH * scale;
        // Vertically centre the logo within availH
        float yOff  = (availH - dstH) * 0.5f;
        dl->AddImage((ImTextureID)(intptr_t)g_logoTex,
            {pos.x, pos.y + yOff}, {pos.x+dstW, pos.y+yOff+dstH},
            {0,0}, {1,1}, C_WHITE);
        ImGui::SetCursorScreenPos(pos);
        ImGui::InvisibleButton("##logo",{dstW,availH});
    } else {
        // Vector fallback
        float r  = availH * 0.45f;
        ImVec2 c = {pos.x + r + 2.f, pos.y + availH * 0.5f};
        dl->AddCircle(c, r, C_ACCENT, 0, 1.5f);
        float r5 = r * 0.55f;
        int   nd = 8;
        float da = 3.14159f*2.f/(float)(nd*2);
        for(int i=0;i<nd;i++){
            float a0=(float)i*2.f*da, a1=a0+da*0.85f;
            dl->PathArcTo(c,r5,a0,a1,4);
            dl->PathStroke(C_ACCENT,false,1.f);
        }
        dl->AddCircleFilled(c, r*0.22f, C_ACCENT);
        float lw=1.5f, tick=r*0.2f;
        dl->AddLine({c.x,c.y-r},{c.x,c.y-r+tick},C_ACCENT,lw);
        dl->AddLine({c.x,c.y+r-tick},{c.x,c.y+r},C_ACCENT,lw);
        dl->AddLine({c.x-r,c.y},{c.x-r+tick,c.y},C_ACCENT,lw);
        dl->AddLine({c.x+r-tick,c.y},{c.x+r,c.y},C_ACCENT,lw);
        ImGui::SetCursorScreenPos(pos);
        ImGui::InvisibleButton("##logo",{r*2.f+4.f,availH});
    }
}

// ─── now-playing card ────────────────────────────────────────
static void DrawNowPlayingCard(ImDrawList* dl, ImVec2 pos, float w)
{
    const float cardH  = 68.f;
    const float padL   = 5.f+3.f;
    const float padR   = 8.f;
    const float padT   = 8.f;
    const float thumbW = 80.f;
    const float thumbH = 45.f;

    dl->AddRectFilled(pos,{pos.x+w,pos.y+cardH},COL32(78,168,168,20));
    dl->AddRectFilled(pos,{pos.x+3.f,pos.y+cardH},C_ACCENT);
    dl->AddLine({pos.x,pos.y+cardH},{pos.x+w,pos.y+cardH},COL32(78,168,168,46),1.f);

    float tx=pos.x+padL, ty=pos.y+padT;
    dl->AddRectFilled({tx,ty},{tx+thumbW,ty+thumbH},g_related[0].grad,3.f);
    dl->AddRectFilled({tx,ty},{tx+thumbW,ty+thumbH},COL32(78,168,168,25),3.f);
    ImVec2 cc={tx+thumbW*.5f,ty+thumbH*.5f};
    dl->AddCircleFilled(cc,11.f,COL32(0,0,0,120));
    IconPlay(dl,cc,6.f,C_ACCENT);

    float ix=tx+thumbW+8.f;
    float iw=w-padL-thumbW-8.f-padR;
    float iy=pos.y+padT;

    dl->PushClipRect({ix,pos.y},{pos.x+w-padR,pos.y+cardH},true);
    const char* badge="NOW PLAYING";
    ImVec2 bsz=TS(badge);
    Txt(dl,{ix,iy},C_ACCENT,badge);
    iy+=bsz.y+2.f;
    Txt(dl,{ix,iy},C_TEXT,g_related[0].title,iw);
    ImVec2 tsz=TS(g_related[0].title,iw);
    iy+=tsz.y+4.f;
    Txt(dl,{ix,iy},C_TEXT_FAINT,g_related[0].channel);
    dl->PopClipRect();
}

// ─── related item ────────────────────────────────────────────
static void DrawRelatedItem(ImDrawList* dl,ImVec2 pos,float w,const RelItem& item,int)
{
    const float thumbW=100.f,thumbH=56.f;
    const float padT=8.f,padL=8.f,padR=8.f;
    const float itemH=thumbH+padT*2.f;

    float tx=pos.x+padL, ty=pos.y+padT;
    dl->AddRectFilled({tx,ty},{tx+thumbW,ty+thumbH},item.grad,3.f);
    ImVec2 ds=TS(item.dur);
    float bx=tx+thumbW-ds.x-7.f, by2=ty+thumbH-14.f;
    dl->AddRectFilled({bx-3.f,by2},{tx+thumbW-3.f,by2+12.f},COL32(0,0,0,200),2.f);
    Txt(dl,{bx,by2+1.f},C_TEXT,item.dur);

    float ix=tx+thumbW+8.f;
    float iw=w-padL-thumbW-8.f-padR;
    float iy=pos.y+padT;

    dl->PushClipRect({ix,pos.y},{pos.x+w-padR,pos.y+itemH},true);
    Txt(dl,{ix,iy},C_TEXT,item.title,iw);
    ImVec2 titSz=TS(item.title,iw);
    float titleH=titSz.y; if(titleH>13.f*2.f+4.f) titleH=13.f*2.f+4.f;
    iy+=titleH+4.f;
    Txt(dl,{ix,iy},C_TEXT_MUTED,item.channel);
    ImVec2 chSz=TS(item.channel);
    iy+=chSz.y+2.f;
    Txt(dl,{ix,iy},C_TEXT_FAINT,item.views);
    dl->PopClipRect();

    dl->AddLine({pos.x+padL,pos.y+itemH-1.f},{pos.x+w-padR,pos.y+itemH-1.f},C_BORDER,1.f);
}

// ─── titlebar ────────────────────────────────────────────────
// FIX (logo): logoAreaH = h-2 (was h-4). DrawLogoArea uses
//   min(availH, texH) as scale base and caps dstW at 140px.
// FIX (nav buttons): background rect is always drawn (faint at
//   rest, brighter on hover, surface2 tint on active press).
//   Chevron lines are drawn AFTER the bg so they are always on
//   top. IsItemActive() drives the pressed state for proper
//   click feedback on XP/Vista D3D9.
static void DrawTitlebar(ImDrawList* dl,ImVec2 pos,float w)
{
    float h=38.f;
    RectFill(dl,pos,{w,h},C_SURFACE);
    dl->AddLine({pos.x,pos.y+h},{pos.x+w,pos.y+h},C_BORDER,1.f);

    float cy=pos.y+h*.5f;
    float x =pos.x+8.f;

    // ── Logo ──────────────────────────────────────────────────
    float logoAreaH = h - 2.f;   // FIX: was h-4
    float logoAreaY = pos.y + 1.f;
    DrawLogoArea(dl, {x, logoAreaY}, logoAreaH);
    if(g_logoTex && g_logoTexH > 0){
        float scaleBase = (logoAreaH < (float)g_logoTexH) ? logoAreaH : (float)g_logoTexH;
        float scale = scaleBase / (float)g_logoTexH;
        float dstW  = (float)g_logoTexW * scale;
        if(dstW > 140.f) dstW = 140.f;
        x += dstW + 12.f;
    } else {
        x += logoAreaH + 12.f;
    }

    // ── Back / Forward nav buttons ────────────────────────────
    // FIX: bg is drawn first (always visible), then chevron on top.
    //      Three visual states: rest / hover / active (pressed).
    {
        const float btnSz = 28.f;
        const float bhalf = btnSz * 0.5f;

        // Back button
        {
            ImVec2 bpos = {x, cy - bhalf};
            ImGui::SetCursorScreenPos(bpos);
            ImGui::InvisibleButton("##navback",{btnSz,btnSz});
            bool hov = ImGui::IsItemHovered();
            bool act = ImGui::IsItemActive();
            // Always draw a faint bg so the button is always findable
            ImU32 bg = act  ? C_SURFACE2 :
                       hov  ? C_SURFACE3 :
                               COL32(255,255,255,8);
            dl->AddRectFilled(bpos,{bpos.x+btnSz,bpos.y+btnSz},bg,4.f);
            if(hov || act)
                dl->AddRect(bpos,{bpos.x+btnSz,bpos.y+btnSz},C_BORDER,4.f,0,1.f);
            // Chevron drawn after bg so it's always on top
            ImU32 arrowCol = (hov || act) ? C_TEXT : C_TEXT_MUTED;
            dl->AddLine({bpos.x+btnSz*.58f,cy-4.f},{bpos.x+btnSz*.38f,cy},arrowCol,1.5f);
            dl->AddLine({bpos.x+btnSz*.38f,cy},{bpos.x+btnSz*.58f,cy+4.f},arrowCol,1.5f);
            x += btnSz + 2.f;
        }

        // Forward button
        {
            ImVec2 bpos = {x, cy - bhalf};
            ImGui::SetCursorScreenPos(bpos);
            ImGui::InvisibleButton("##navfwd",{btnSz,btnSz});
            bool hov = ImGui::IsItemHovered();
            bool act = ImGui::IsItemActive();
            ImU32 bg = act  ? C_SURFACE2 :
                       hov  ? C_SURFACE3 :
                               COL32(255,255,255,8);
            dl->AddRectFilled(bpos,{bpos.x+btnSz,bpos.y+btnSz},bg,4.f);
            if(hov || act)
                dl->AddRect(bpos,{bpos.x+btnSz,bpos.y+btnSz},C_BORDER,4.f,0,1.f);
            ImU32 arrowCol = (hov || act) ? C_TEXT : C_TEXT_MUTED;
            dl->AddLine({bpos.x+btnSz*.42f,cy-4.f},{bpos.x+btnSz*.62f,cy},arrowCol,1.5f);
            dl->AddLine({bpos.x+btnSz*.62f,cy},{bpos.x+btnSz*.42f,cy+4.f},arrowCol,1.5f);
            x += btnSz + 8.f;
        }
    }

    // ── Nav links ─────────────────────────────────────────────
    {
        const char* navs[]={"Home","Trending","Library","History"};
        for(int i=0;i<4;i++){
            ImVec2 ts2=TS(navs[i]);
            float tw=ts2.x+8.f;
            ImGui::SetCursorScreenPos({x,pos.y+6.f});
            char navId[32]; snprintf(navId,sizeof(navId),"##nav%d",i);
            ImGui::InvisibleButton(navId,{tw,h-6.f});
            bool hov=ImGui::IsItemHovered();
            ImU32 tc=(i==0)?C_TEXT:(hov?C_TEXT:C_TEXT_MUTED);
            Txt(dl,{x,cy-ts2.y*.5f},tc,navs[i]);
            if(i==0) dl->AddRectFilled({x,pos.y+h-2.f},{x+ts2.x,pos.y+h},C_ACCENT);
            x+=tw+4.f;
        }
    }

    // ── Search bar + settings ─────────────────────────────────
    float rightPad=12.f, settingsSz=28.f, searchW=160.f, searchH=26.f;
    float searchX=pos.x+w-rightPad-settingsSz-4.f-searchW;
    float searchY=cy-searchH*.5f;
    RectFill(dl,{searchX,searchY},{searchW,searchH},C_SURFACE3,5.f);
    Rect(dl,{searchX,searchY},{searchW,searchH},C_BORDER,5.f);
    ImVec2 pt=TS(g_search);
    Txt(dl,{searchX+8.f,searchY+(searchH-pt.y)*.5f},C_TEXT_FAINT,g_search);
    float sbW=52.f, sbX=searchX+searchW-sbW;
    dl->AddRectFilled({sbX,searchY+1.f},{searchX+searchW-1.f,searchY+searchH-1.f},C_ACCENT,4.f);
    const char* srchLbl="Search";
    ImVec2 sl=TS(srchLbl);
    Txt(dl,{sbX+(sbW-sl.x)*.5f,searchY+(searchH-sl.y)*.5f},C_WHITE,srchLbl);

    float sx2=pos.x+w-rightPad-settingsSz, sy2=cy-settingsSz*.5f;
    ImGui::SetCursorScreenPos({sx2,sy2});
    ImGui::InvisibleButton("##settings",{settingsSz,settingsSz});
    bool sHov=ImGui::IsItemHovered();
    if(sHov) dl->AddRectFilled({sx2,sy2},{sx2+settingsSz,sy2+settingsSz},C_SURFACE3,4.f);
    IconDots(dl,{sx2+settingsSz*.5f,cy},7.f,C_TEXT_MUTED);
}

// ─── video area ──────────────────────────────────────────────
static void DrawVideoArea(ImDrawList* dl,ImVec2 pos,float w,float h)
{
    RectFill(dl,pos,{w,h},C_BLACK);
    dl->AddRectFilledMultiColor(pos,{pos.x+w,pos.y+h},
        COL32(0,0,0,0),COL32(0,0,0,0),COL32(