// ============================================================
//  Sightline — Video Player UI
//  Dear ImGui + Win32 + Direct3D9
//  Single EXE, compatible Windows XP SP3 x86 -> Windows 11
//  Compiler: MinGW-w64 i686
// ============================================================

#define WINVER       0x0501
#define _WIN32_WINNT 0x0501
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <d3d9.h>
// WIC GUIDs are resolved via libuuid.a at link time (-luuid).
// Do NOT use #define INITGUID here — it does not work for WIC
// GUIDs with mingw-w64; -luuid in the link step is the fix.
#include <wincodec.h>

#include "imgui.h"
#include "imgui_impl_win32.h"
#include "imgui_impl_dx9.h"

// ── Embedded Electrolize font ─────────────────────────────────
// font_electrolize.h is always present (stub or real).
// CI overwrites it with real TTF bytes before compiling.
// IMPORTANT: HAS_ELECTROLIZE_EMBED must be a plain 0/1 integer
// constant so that #if works at preprocessor time.
// The stub commits len=0 so we define the macro to 0 here;
// the CI regenerates this file with len>0 before building.
#include "font_electrolize.h"
// Runtime check — DO NOT use #if here; use a regular if() below.
static inline bool HasElectrolize() { return electrolize_regular_ttf_len > 4; }

// ── Embedded logo PNG ─────────────────────────────────────────
// logo_data.h is generated by CI from src/Sightline Logo.png
#if __has_include("logo_data.h")
  #include "logo_data.h"
  static inline bool HasLogo() { return sightline_logo_png_len > 4; }
#else
  static const unsigned char sightline_logo_png[]   = {0};
  static const unsigned int  sightline_logo_png_len = 0;
  static inline bool HasLogo() { return false; }
#endif

#include <cstdio>
#include <cmath>
#include <cstring>
#include <string>

// ─── colour palette ──────────────────────────────────────────
#define COL32(r,g,b,a) IM_COL32(r,g,b,a)
static const ImU32 C_BG          = COL32(0x0C,0x10,0x14,255);
static const ImU32 C_SURFACE     = COL32(0x13,0x19,0x20,255);
static const ImU32 C_SURFACE2    = COL32(0x19,0x20,0x28,255);
static const ImU32 C_SURFACE3    = COL32(0x1E,0x26,0x2F,255);
static const ImU32 C_DIVIDER     = COL32(0x1B,0x22,0x29,255);
static const ImU32 C_BORDER      = COL32(255,255,255,18);
static const ImU32 C_BORDER_STR  = COL32(255,255,255,31);
static const ImU32 C_TEXT        = COL32(0xE6,0xED,0xF2,255);
static const ImU32 C_TEXT_MUTED  = COL32(0x8A,0x97,0xA3,255);
static const ImU32 C_TEXT_FAINT  = COL32(0x4D,0x5E,0x69,255);
static const ImU32 C_ACCENT      = COL32(0x4E,0xA8,0xA8,255);
static const ImU32 C_ACCENT_HOV  = COL32(0x62,0xBC,0xBC,255);
static const ImU32 C_ACCENT_SOFT = COL32(78,168,168,31);
static const ImU32 C_ACCENT_LINE = COL32(78,168,168,89);
static const ImU32 C_SUCCESS     = COL32(0x6B,0xAA,0x78,255);
static const ImU32 C_ERROR       = COL32(0xC9,0x6B,0x6B,255);
static const ImU32 C_BLACK       = COL32(0,0,0,255);
static const ImU32 C_WHITE       = COL32(0xFF,0xFF,0xFF,255);

static inline ImVec4 U32toV4(ImU32 c){
    return ImVec4(((c>>0)&0xFF)/255.f,((c>>8)&0xFF)/255.f,
                  ((c>>16)&0xFF)/255.f,((c>>24)&0xFF)/255.f);
}

// ─── glyph ranges ────────────────────────────────────────────
static const ImWchar g_glyph_ranges[] = {
    0x0020,0x00FF, 0x0100,0x024F, 0x2000,0x206F, 0x20AC,0x20AC, 0,
};

// ─── font handles ────────────────────────────────────────────
static ImFont* g_font13 = nullptr;
static ImFont* g_font16 = nullptr;

// ─── logo DX9 texture ────────────────────────────────────────
static LPDIRECT3DTEXTURE9 g_logoTex    = NULL;
static int                g_logoTexW   = 0;
static int                g_logoTexH   = 0;

// ─── app state ───────────────────────────────────────────────
static float  g_seek       = 0.175f;
static float  g_vol        = 0.80f;
static bool   g_playing    = true;
static int    g_tab        = 0;
static int    g_quality    = 0;
static bool   g_subscribed = false;
static char   g_search[128]= "rickroll";
static float  g_sideScroll = 0.f;

static const char* g_qualityOpts[] = {"2160p","1080p","720p","480p"};
static const int   g_qualityCount  = 4;

struct RelItem { const char* title; const char* channel; const char* views; const char* dur; ImU32 grad; };
static const RelItem g_related[] = {
    {"Rick Astley \xe2\x80\x94 Never Gonna Give You Up (Official Video) 4K Remaster","Rick Astley","1.7B views","3:33",COL32(0x13,0x19,0x20,255)},
    {"Best of 80s Music Legends \xe2\x80\x94 Team Formidable Mix","Radio 80s Hits","2.1M views","42:18",COL32(0x1a,0x20,0x30,255)},
    {"Rick Astley \xe2\x80\x94 Mix de Exitos Completo","Nanojams300","890K views","31:08",COL32(0x1a,0x28,0x20,255)},
    {"Daft Punk ft. Pharrell Williams \xe2\x80\x94 Get Lucky (Official)","pftpremials","1.4B views","3:44",COL32(0x20,0x18,0x28,255)},
    {"Shakira, Burna Boy \xe2\x80\x94 Dai Dai (Official Video)","shakiriaVEVO","420M views","3:59",COL32(0x28,0x18,0x20,255)},
    {"Phil Collins, Rod Stewart \xe2\x80\x94 Soulful 80s Mix","Soft Rock Soulful","3.2M views","4:07",COL32(0x18,0x20,0x28,255)},
    {"George Michael \xe2\x80\x94 Careless Whisper (Official 4K)","georgemc.feel","1.1B views","5:11",COL32(0x28,0x20,0x18,255)},
    {"Ultimate 80s Classics: Timeless Icons Mix","Flashback Grooves","5.7M views","58:01",COL32(0x18,0x18,0x28,255)},
    {"Eagles \xe2\x80\x94 Hotel California (Live 1977 Official)","Eagles","987M views","8:45",COL32(0x20,0x18,0x20,255)},
};
static const int g_relatedCount = 9;

// ─── D3D9 globals ────────────────────────────────────────────
static LPDIRECT3D9           g_pD3D    = NULL;
static LPDIRECT3DDEVICE9     g_pd3dDev = NULL;
static D3DPRESENT_PARAMETERS g_d3dpp   = {};
static HWND                  g_hwnd    = NULL;

static bool CreateDeviceD3D(HWND hWnd)
{
    if((g_pD3D = Direct3DCreate9(D3D_SDK_VERSION)) == NULL) return false;
    ZeroMemory(&g_d3dpp,sizeof(g_d3dpp));
    g_d3dpp.Windowed               = TRUE;
    g_d3dpp.SwapEffect             = D3DSWAPEFFECT_DISCARD;
    g_d3dpp.BackBufferFormat       = D3DFMT_UNKNOWN;
    g_d3dpp.EnableAutoDepthStencil = TRUE;
    g_d3dpp.AutoDepthStencilFormat = D3DFMT_D16;
    g_d3dpp.PresentationInterval   = D3DPRESENT_INTERVAL_ONE;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_HARDWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    if(g_pD3D->CreateDevice(D3DADAPTER_DEFAULT,D3DDEVTYPE_HAL,hWnd,
        D3DCREATE_SOFTWARE_VERTEXPROCESSING,&g_d3dpp,&g_pd3dDev)==D3D_OK) return true;
    return false;
}
static void CleanupDevice()
{
    if(g_logoTex){ g_logoTex->Release(); g_logoTex=NULL; }
    if(g_pd3dDev){ g_pd3dDev->Release(); g_pd3dDev=NULL; }
    if(g_pD3D)   { g_pD3D->Release();    g_pD3D=NULL; }
}
static void ResetDevice()
{
    ImGui_ImplDX9_InvalidateDeviceObjects();
    g_pd3dDev->Reset(&g_d3dpp);
    ImGui_ImplDX9_CreateDeviceObjects();
}

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND,UINT,WPARAM,LPARAM);
static LRESULT WINAPI WndProc(HWND hWnd,UINT msg,WPARAM wParam,LPARAM lParam)
{
    if(ImGui_ImplWin32_WndProcHandler(hWnd,msg,wParam,lParam)) return true;
    switch(msg){
        case WM_SIZE:
            if(g_pd3dDev && wParam!=SIZE_MINIMIZED){
                g_d3dpp.BackBufferWidth  = LOWORD(lParam);
                g_d3dpp.BackBufferHeight = HIWORD(lParam);
                ResetDevice();
            }
            return 0;
        case WM_DESTROY: PostQuitMessage(0); return 0;
    }
    return DefWindowProcA(hWnd,msg,wParam,lParam);
}

// ─── WIC PNG loader → DX9 texture ────────────────────────────
// Uses Windows Imaging Component (XP SP3+). No GDI+, no extra libs.
static bool LoadPNGFromMemory(const unsigned char* data, unsigned int len,
                               LPDIRECT3DDEVICE9 dev,
                               LPDIRECT3DTEXTURE9* outTex, int* outW, int* outH)
{
    if(!data || len==0 || !dev || !outTex || !outW || !outH) return false;

    IWICImagingFactory*    wicFactory = NULL;
    IWICStream*            wicStream  = NULL;
    IWICBitmapDecoder*     decoder    = NULL;
    IWICBitmapFrameDecode* frame      = NULL;
    IWICFormatConverter*   converter  = NULL;
    bool ok = false;

    if(FAILED(CoCreateInstance(CLSID_WICImagingFactory, NULL,
        CLSCTX_INPROC_SERVER, IID_IWICImagingFactory,
        (void**)&wicFactory))) goto cleanup;

    if(FAILED(wicFactory->CreateStream(&wicStream))) goto cleanup;
    if(FAILED(wicStream->InitializeFromMemory(
        const_cast<BYTE*>(data), len))) goto cleanup;
    if(FAILED(wicFactory->CreateDecoderFromStream(
        wicStream, NULL,
        WICDecodeMetadataCacheOnLoad, &decoder))) goto cleanup;
    if(FAILED(decoder->GetFrame(0, &frame))) goto cleanup;

    {
        UINT w=0, h=0;
        if(FAILED(frame->GetSize(&w, &h))) goto cleanup;

        if(FAILED(wicFactory->CreateFormatConverter(&converter))) goto cleanup;
        if(FAILED(converter->Initialize(
            frame,
            GUID_WICPixelFormat32bppBGRA,
            WICBitmapDitherTypeNone, NULL, 0.0,
            WICBitmapPaletteTypeCustom))) goto cleanup;

        LPDIRECT3DTEXTURE9 tex = NULL;
        if(FAILED(dev->CreateTexture(w, h, 1, 0, D3DFMT_A8R8G8B8,
            D3DPOOL_MANAGED, &tex, NULL))) goto cleanup;

        D3DLOCKED_RECT lr;
        if(FAILED(tex->LockRect(0, &lr, NULL, 0))){
            tex->Release(); goto cleanup;
        }
        UINT stride = w * 4;
        converter->CopyPixels(NULL, stride, h * stride, (BYTE*)lr.pBits);
        tex->UnlockRect(0);

        *outTex = tex;
        *outW   = (int)w;
        *outH   = (int)h;
        ok = true;
    }

cleanup:
    if(converter)  converter->Release();
    if(frame)      frame->Release();
    if(decoder)    decoder->Release();
    if(wicStream)  wicStream->Release();
    if(wicFactory) wicFactory->Release();
    return ok;
}

// ─── helpers ─────────────────────────────────────────────────
static void RectFill(ImDrawList* dl,ImVec2 p,ImVec2 s,ImU32 col,float r=0.f)
    { dl->AddRectFilled(p,{p.x+s.x,p.y+s.y},col,r); }
static void Rect(ImDrawList* dl,ImVec2 p,ImVec2 s,ImU32 col,float r=0.f,float t=1.f)
    { dl->AddRect(p,{p.x+s.x,p.y+s.y},col,r,0,t); }
static void Txt(ImDrawList* dl,ImVec2 p,ImU32 col,const char* s)
    { dl->AddText(p,col,s); }
static ImVec2 TS(const char* s){ return ImGui::CalcTextSize(s); }

// ─── icon primitives ─────────────────────────────────────────
static void IconPlay(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    dl->AddTriangleFilled({c.x-r*.6f,c.y-r},{c.x-r*.6f,c.y+r},{c.x+r*.9f,c.y},col);
}
static void IconPause(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.35f,hh=r*.9f;
    dl->AddRectFilled({c.x-hw*2.2f,c.y-hh},{c.x-hw*.4f,c.y+hh},col,1.f);
    dl->AddRectFilled({c.x+hw*.4f, c.y-hh},{c.x+hw*2.2f,c.y+hh},col,1.f);
}
static void IconVolume(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.4f,hh=r*.6f;
    dl->AddTriangleFilled({c.x-r,c.y-hh},{c.x-r,c.y+hh},{c.x-r*.1f,c.y},col);
    dl->AddRectFilled({c.x-r*.1f,c.y-hh*.4f},{c.x,c.y+hh*.4f},col,0.f);
    float x0=c.x+r*.08f;
    dl->PathArcTo({x0,c.y},r*.5f,-0.6f,0.6f,8); dl->PathStroke(col,false,1.3f);
    dl->PathArcTo({x0,c.y},r*.85f,-0.7f,0.7f,8); dl->PathStroke(col,false,1.3f);
}
static void IconFullscreen(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float s=r*.65f,t=r*.25f;
    auto corner=[&](float sx,float sy){
        dl->AddLine({c.x+sx*s,c.y+sy*s},{c.x+sx*(s-t),c.y+sy*s},col,1.3f);
        dl->AddLine({c.x+sx*s,c.y+sy*s},{c.x+sx*s,c.y+sy*(s-t)},col,1.3f);
    };
    corner(-1,-1); corner(1,-1); corner(-1,1); corner(1,1);
}
static void IconShare(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float nx=c.x-r*.3f;
    dl->AddCircleFilled({c.x+r*.5f,c.y-r*.5f},r*.22f,col,8);
    dl->AddCircleFilled({c.x+r*.5f,c.y+r*.5f},r*.22f,col,8);
    dl->AddCircleFilled({c.x-r*.5f,c.y},r*.22f,col,8);
    dl->AddLine({c.x-r*.5f,c.y},{c.x+r*.5f,c.y-r*.5f},col,1.2f);
    dl->AddLine({c.x-r*.5f,c.y},{c.x+r*.5f,c.y+r*.5f},col,1.2f);
    (void)nx;
}
static void IconDownload(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r*.35f,top=c.y-r*.6f,bot=c.y+r*.1f;
    dl->AddLine({c.x,top},{c.x,bot},col,1.4f);
    dl->AddTriangleFilled({c.x-hw,bot},{c.x+hw,bot},{c.x,bot+r*.5f},col);
    dl->AddLine({c.x-r*.7f,c.y+r*.7f},{c.x+r*.7f,c.y+r*.7f},col,1.4f);
}
static void IconDots(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float sp=r*.5f,dr=r*.18f;
    dl->AddCircleFilled({c.x-sp,c.y},dr,col,6);
    dl->AddCircleFilled({c.x,   c.y},dr,col,6);
    dl->AddCircleFilled({c.x+sp,c.y},dr,col,6);
}
static void IconThumbUp(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r,hh=r*.8f,stem=r*.45f;
    dl->PathLineTo({c.x-hw,c.y+hh});
    dl->PathLineTo({c.x-hw,c.y});
    dl->PathLineTo({c.x-hw*.3f,c.y-hh});
    dl->PathLineTo({c.x+hw*.5f,c.y-hh});
    dl->PathLineTo({c.x+hw,c.y-hh*.3f});
    dl->PathLineTo({c.x+hw*.7f,c.y+hh*.2f});
    dl->PathLineTo({c.x,c.y+hh*.2f});
    dl->PathLineTo({c.x,c.y+hh});
    dl->PathStroke(col,true,1.3f);
    dl->AddRectFilled({c.x-hw,c.y-hh*.1f},{c.x-hw+r*.22f,c.y-hh*.1f+r*.1f},col,1.f);
    (void)stem;
}
static void IconThumbDown(ImDrawList* dl,ImVec2 c,float r,ImU32 col)
{
    float hw=r,hh=r*.8f;
    dl->PathLineTo({c.x-hw,c.y-hh});
    dl->PathLineTo({c.x-hw,c.y});
    dl->PathLineTo({c.x-hw*.3f,c.y+hh});
    dl->PathLineTo({c.x+hw*.5f,c.y+hh});
    dl->PathLineTo({c.x+hw,c.y+hh*.3f});
    dl->PathLineTo({c.x+hw*.7f,c.y-hh*.2f});
    dl->PathLineTo({c.x,c.y-hh*.2f});
    dl->PathLineTo({c.x,c.y-hh});
    dl->PathStroke(col,true,1.3f);
    dl->AddRectFilled({c.x-hw,c.y+hh*.1f},{c.x-hw+r*.22f,c.y+hh*.1f-r*.1f},col,1.f);
}

// IconSkip — standard "circular arrow + number" media icon.
// Open circle arc (~280°) with a filled arrowhead at the open end,
// and the number "10" centred inside the arc ring.
// forward=true  → clockwise arc, arrowhead points right  (+10s)
// forward=false → counter-clockwise arc, arrowhead points left (-10s)
static void IconSkip(ImDrawList* dl, ImVec2 c, float r, ImU32 col, bool forward)
{
    const float PI   = 3.14159265f;
    const float arcR = r * 0.82f;  // arc radius

    // Arc: ~280° sweep.  For +10 the arc runs clockwise from ~+32° back to ~-32°
    // (leaving a ~80° gap at the top-right).  For -10 it mirrors horizontally.
    // ImGui PathArcTo draws CCW when a_min < a_max.
    // We want a CW arc for forward and CCW for backward — just swap the angles:
    //   fwd:  from  PI*1.82  to  PI*(-0.18)   → winds ~280° CW (passes through bottom)
    //   bwd:  from  PI*0.18  to  PI*2.18       → winds ~280° CCW (mirrors fwd)
    if(forward){
        dl->PathArcTo(c, arcR,  PI*1.82f,  -PI*0.18f, 20);
    } else {
        dl->PathArcTo(c, arcR,  PI*0.18f,   PI*2.18f, 20);
    }
    dl->PathStroke(col, false, 1.5f);

    // Arrowhead: sits at the open end of the arc.
    // fwd end angle = -PI*0.18 (~-32°), bwd end angle = PI*0.18 (~+32°)
    float tipAng  = forward ? (-PI * 0.18f) : (PI * 0.18f);
    // Tangent at the tip, oriented in the direction the arc was travelling:
    //   fwd arc travels CW  → tangent points  "downward-right" at the end  = tipAng - PI/2
    //   bwd arc travels CCW → tangent points  "downward-left"  at the end  = tipAng + PI/2
    float tangAng = forward ? (tipAng - PI * 0.5f) : (tipAng + PI * 0.5f);
    float tx = c.x + arcR * cosf(tipAng);
    float ty = c.y + arcR * sinf(tipAng);
    float hs = r * 0.30f;  // arrowhead half-size
    ImVec2 tip = {tx, ty};
    ImVec2 lft = {tx + hs*cosf(tangAng + PI*0.68f), ty + hs*sinf(tangAng + PI*0.68f)};
    ImVec2 rgt = {tx + hs*cosf(tangAng - PI*0.68f), ty + hs*sinf(tangAng - PI*0.68f)};
    dl->AddTriangleFilled(tip, lft, rgt, col);

    // "10" centred inside the arc circle, shifted slightly toward the closed side
    const char* num = "10";
    ImVec2 ns = TS(num);
    float offX = forward ? -r * 0.04f : r * 0.04f;
    dl->AddText(g_font13, 13.f,
        {c.x - ns.x * 0.5f + offX, c.y - ns.y * 0.5f + r * 0.04f},
        col, num);
}

// ─── seekbar / volbar ─────────────────────────────────────────
static bool SeekBar(ImDrawList* dl,ImVec2 pos,float width,float height,
                    float* val,float buf,ImU32 cRail,ImU32 cBuf,ImU32 cFill,ImU32 cThumb)
{
    // Hit area covers the full bar width
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton("##seek",{width,height});
    bool hov=ImGui::IsItemHovered();
    bool act=ImGui::IsItemActive();
    bool changed=false;

    // FIX: padX increased to 8 so the thumb circle (r=5.5) is fully
    // contained within the widget at val=0 and val=1.
    const float padX   = 8.f;
    const float railX0 = pos.x + padX;
    const float railW  = width - padX * 2.f;

    if(act){
        float mx=ImGui::GetIO().MousePos.x;
        *val=(mx - railX0) / railW;
        if(*val<0.f)*val=0.f; if(*val>1.f)*val=1.f;
        changed=true;
    }

    float fillW = railW * (*val);
    float bufW  = railW * buf;
    float cy    = pos.y + height * .5f;
    float rh    = 3.f, ry = cy - rh * .5f;

    // Rail
    dl->AddRectFilled({railX0,ry},{railX0+railW,ry+rh},cRail,2.f);
    // Buffer
    dl->AddRectFilled({railX0,ry},{railX0+bufW, ry+rh},cBuf, 2.f);
    // Fill
    dl->AddRectFilled({railX0,ry},{railX0+fillW,ry+rh},cFill,2.f);
    // Thumb
    if(hov||act){
        float tx=railX0+fillW;
        dl->AddCircleFilled({tx,cy},5.5f,cThumb);
    }
    return changed;
}

static bool VolBar(ImDrawList* dl,ImVec2 pos,float width,float height,float* val)
{
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton("##vol",{width,height});
    bool hov=ImGui::IsItemHovered();
    bool act=ImGui::IsItemActive();

    const float padX   = 8.f;
    const float railX0 = pos.x + padX;
    const float railW  = width - padX * 2.f;

    if(act){
        float mx=ImGui::GetIO().MousePos.x;
        *val=(mx - railX0) / railW;
        if(*val<0.f)*val=0.f; if(*val>1.f)*val=1.f;
    }
    float fillW=railW*(*val);
    float cy=pos.y+height*.5f;
    float rh=3.f,ry=cy-rh*.5f;
    dl->AddRectFilled({railX0,ry},{railX0+railW,ry+rh},COL32(255,255,255,25),2.f);
    dl->AddRectFilled({railX0,ry},{railX0+fillW, ry+rh},C_TEXT,2.f);
    if(hov||act){
        float tx=railX0+fillW;
        dl->AddCircleFilled({tx,cy},5.f,C_TEXT);
    }
    return act;
}

static bool IconBtn(const char* id,ImVec2 pos,float sz)
{
    ImGui::SetCursorScreenPos(pos);
    ImGui::InvisibleButton(id,{sz,sz});
    bool hov=ImGui::IsItemHovered();
    if(hov){
        ImGui::GetWindowDrawList()->AddRectFilled(pos,{pos.x+sz,pos.y+sz},
            COL32(255,255,255,20),4.f);
    }
    return ImGui::IsItemActivated();
}

// ─── logo sprite helpers ──────────────────────────────────────
#include "logo_sprite.h"

// ─── titlebar ────────────────────────────────────────────────
static void DrawTitlebar(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h=38.f;
    RectFill(dl,pos,{w,h},C_SURFACE);
    dl->AddLine(pos,{pos.x+w,pos.y},C_BORDER,1.f);
    dl->AddLine({pos.x,pos.y+h},{pos.x+w,pos.y+h},C_BORDER,1.f);

    // ── Logo (left) ───────────────────────────────────────────
    if(g_logoTex && g_logoTexW>0 && g_logoTexH>0){
        // Fit the logo PNG into the titlebar, capped at 140px wide.
        float logoAreaH = h + 16.f;
        float logoAreaY = pos.y + (h - logoAreaH) * 0.5f;
        float aspect    = (float)g_logoTexW / (float)g_logoTexH;
        float dstW      = logoAreaH * aspect;
        if(dstW > 140.f){ dstW = 140.f; logoAreaH = dstW / aspect; logoAreaY = pos.y+(h-logoAreaH)*.5f; }
        float logoX = pos.x + 8.f;
        float logoY = logoAreaY;
        ImGui::SetCursorScreenPos({logoX, pos.y});
        ImGui::InvisibleButton("##logo",{dstW,h});
        dl->AddImage((ImTextureID)(uintptr_t)g_logoTex,
            {logoX,logoY},{logoX+dstW,logoY+logoAreaH});
    } else {
        // Fallback: inline animated accent dot (no external sprite needed)
        float r=9.f;
        float logoX=pos.x+r+8.f, logoY=pos.y+h*.5f;
        ImGui::SetCursorScreenPos({logoX-r-4.f, pos.y});
        ImGui::InvisibleButton("##logo",{r*2.f+4.f,h});
        float t=(float)ImGui::GetTime();
        dl->AddCircle({logoX,logoY},r,C_ACCENT,16,1.5f);
        float ax=logoX+r*0.6f*cosf(t*2.f), ay=logoY+r*0.6f*sinf(t*2.f);
        dl->AddCircleFilled({ax,ay},3.f,C_ACCENT,8);
    }

    // ── Nav tabs (centre) ─────────────────────────────────────
    const char* navs[]={"Home","Explore","Library","History"};
    const int nNavs=4;
    float totalW=0.f;
    for(int i=0;i<nNavs;i++) totalW+=TS(navs[i]).x+24.f;
    float nx=pos.x+(w-totalW)*.5f;
    float cy=pos.y+h*.5f;

    for(int i=0;i<nNavs;i++){
        ImVec2 ts=TS(navs[i]);
        float tw=ts.x+24.f;
        bool sel=(i==g_tab);
        ImU32 tc=sel?C_TEXT:C_TEXT_MUTED;
        ImGui::SetCursorScreenPos({nx,pos.y+3.f});
        const char* navId=(i==0?"##nav0":i==1?"##nav1":i==2?"##nav2":"##nav3");
        if(ImGui::InvisibleButton(navId,{tw,h-6.f})) g_tab=i;
        if(ImGui::IsItemHovered()&&!sel) tc=C_TEXT;
        Txt(dl,{nx+(tw-ts.x)*.5f,cy-ts.y*.5f},tc,navs[i]);
        if(sel){
            dl->AddRectFilled({nx+4.f,pos.y+h-3.f},{nx+tw-4.f,pos.y+h},C_ACCENT,2.f);
        }
        nx+=tw;
    }

    // ── Search bar (right) ────────────────────────────────────
    float searchH=26.f, searchW=180.f;
    float searchX=pos.x+w-searchW-10.f;
    float searchY=cy-searchH*.5f;
    RectFill(dl,{searchX,searchY},{searchW,searchH},C_SURFACE2,5.f);
    Rect(dl,{searchX,searchY},{searchW,searchH},C_BORDER,5.f);
    ImGui::SetCursorScreenPos({searchX+8.f,searchY+3.f});
    ImGui::SetNextItemWidth(searchW-18.f);
    ImGui::PushStyleColor(ImGuiCol_FrameBg,IM_COL32(0,0,0,0));
    ImGui::PushStyleColor(ImGuiCol_Text,IM_COL32(0xE6,0xED,0xF2,255));
    ImGui::InputText("##search",g_search,sizeof(g_search));
    ImGui::PopStyleColor(2);

    // ── Settings dots (far right) ─────────────────────────────
    float settingsSz=24.f;
    float sx2=pos.x+w-settingsSz*.5f-4.f, sy2=cy-settingsSz*.5f;
    ImGui::SetCursorScreenPos({sx2,sy2});
    ImGui::InvisibleButton("##settings",{settingsSz,settingsSz});
    bool shov=ImGui::IsItemHovered();
    IconDots(dl,{sx2+settingsSz*.5f,cy},7.f,shov?C_TEXT:C_TEXT_MUTED);
}

// ─── controls bar ────────────────────────────────────────────
// Layout (top→bottom, bar height = 72px):
//
//   [0 .. 8]    top padding
//   [8 .. 22]   seek rail hit-area  (14 px tall)
//   [22.. 40]   time labels row     (rendered at seekY+seekH+2, ~13px tall)
//               → bottom of text ≈ Y+35, leaving ~4px gap before buttons
//   [40.. 72]   buttons / volume / quality row  (cy at bar_top+54)
//
static void DrawControls(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h      = 72.f;
    const float seekH  = 14.f;
    const float seekY  = pos.y + 8.f;

    RectFill(dl,pos,{w,h},C_SURFACE);
    dl->AddLine(pos,{pos.x+w,pos.y},C_BORDER,1.f);

    // ── Seek rail ─────────────────────────────────────────────
    SeekBar(dl,{pos.x,seekY},w,seekH,&g_seek,0.42f,
        COL32(255,255,255,25),COL32(78,168,168,60),C_ACCENT,C_TEXT);

    // ── Time labels ───────────────────────────────────────────
    {
        const float timeY = seekY + seekH + 2.f;
        int totalSec=600, curSec=(int)(g_seek*totalSec);
        char cur[16]; snprintf(cur,sizeof(cur),"%d:%02d",curSec/60,curSec%60);
        const char* tot="10:00";
        dl->PushClipRect({pos.x,pos.y},{pos.x+w,pos.y+h},true);
        Txt(dl,{pos.x+6.f, timeY},C_TEXT_FAINT,cur);
        ImVec2 ts2=TS(tot);
        Txt(dl,{pos.x+w-ts2.x-6.f, timeY},C_TEXT_FAINT,tot);
        dl->PopClipRect();
    }

    // ── Button / control row ──────────────────────────────────
    const float cy = pos.y + 54.f;
    float x = pos.x + 12.f;

    // Play/Pause
    {
        const float btnSz = 28.f;
        const float bhalf = btnSz * 0.5f;
        ImVec2 bpos = {x, cy - bhalf};
        ImGui::SetCursorScreenPos(bpos);
        ImGui::InvisibleButton("##pp",{btnSz,btnSz});
        bool hov = ImGui::IsItemHovered();
        if(ImGui::IsItemActivated()) g_playing = !g_playing;
        ImU32 bg = hov ? C_SURFACE3 : C_SURFACE2;
        dl->AddRectFilled(bpos,{bpos.x+btnSz,bpos.y+btnSz},bg,5.f);
        dl->AddRect(bpos,{bpos.x+btnSz,bpos.y+btnSz},hov?C_BORDER_STR:C_BORDER,5.f,0,1.f);
        ImVec2 ic = {bpos.x + btnSz * 0.5f, bpos.y + btnSz * 0.5f};
        if(g_playing) IconPause(dl,ic,8.f,C_TEXT);
        else          IconPlay (dl,ic,8.f,C_TEXT);
        x += btnSz + 4.f;
    }

    // Rewind -10s
    {
        const float bsz = 28.f;
        ImVec2 bpos = {x, cy - bsz * 0.5f};
        ImGui::SetCursorScreenPos(bpos);
        ImGui::InvisibleButton("##m10",{bsz,bsz});
        bool hov     = ImGui::IsItemHovered();
        bool clicked = ImGui::IsItemActivated();
        if(hov) dl->AddRectFilled(bpos,{bpos.x+bsz,bpos.y+bsz},COL32(255,255,255,20),4.f);
        IconSkip(dl,{x + bsz * 0.5f, cy},11.f,C_TEXT_MUTED,false);
        if(clicked){ g_seek -= 10.f/600.f; if(g_seek<0.f) g_seek=0.f; }
        x += bsz + 4.f;
    }

    // Forward +10s
    {
        const float bsz = 28.f;
        ImVec2 bpos = {x, cy - bsz * 0.5f};
        ImGui::SetCursorScreenPos(bpos);
        ImGui::InvisibleButton("##p10",{bsz,bsz});
        bool hov     = ImGui::IsItemHovered();
        bool clicked = ImGui::IsItemActivated();
        if(hov) dl->AddRectFilled(bpos,{bpos.x+bsz,bpos.y+bsz},COL32(255,255,255,20),4.f);
        IconSkip(dl,{x + bsz * 0.5f, cy},11.f,C_TEXT_MUTED,true);
        if(clicked){ g_seek += 10.f/600.f; if(g_seek>1.f) g_seek=1.f; }
        x += bsz + 4.f;
    }

    // Volume icon + slider
    {
        const float iconW = 22.f;
        IconVolume(dl,{x+iconW*.5f,cy},9.f,C_TEXT_MUTED);
        x += iconW + 4.f;
    }
    VolBar(dl,{x,cy-7.f},72.f,14.f,&g_vol);
    x += 72.f + 6.f;

    float rx=pos.x+w-12.f;

    // Fullscreen (right-anchored)
    rx-=26.f;
    if(IconBtn("##fs",{rx,cy-13.f},26.f)){}
    IconFullscreen(dl,{rx+13.f,cy},9.f,C_TEXT_MUTED);

    // Quality badge
    rx-=66.f;
    {
        const float qW=60.f, qH=22.f;
        const float qX=rx, qY=cy-qH*.5f;
        RectFill(dl,{qX,qY},{qW,qH},C_SURFACE2,5.f);
        Rect(dl,{qX,qY},{qW,qH},C_BORDER,5.f);
        ImGui::SetCursorScreenPos({qX,qY});
        ImGui::InvisibleButton("##qual",{qW,qH});
        if(ImGui::IsItemActivated()) g_quality=(g_quality+1)%g_qualityCount;
        const char* qlbl=g_qualityOpts[g_quality];
        ImVec2 qts=TS(qlbl);
        Txt(dl,{qX+(qW-qts.x)*.5f, qY+(qH-qts.y)*.5f},C_ACCENT,qlbl);
    }
}

// ─── action bar ──────────────────────────────────────────────
static void DrawActionBar(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h=46.f,btnH=30.f,iconR=6.5f,padLR=10.f,gap=4.f;
    RectFill(dl,pos,{w,h},C_SURFACE);
    dl->AddLine(pos,{pos.x+w,pos.y},C_BORDER,1.f);

    float x=pos.x+10.f;
    const float cy=pos.y+h*.5f, by=cy-btnH*.5f;

    ImDrawList* wdl=ImGui::GetWindowDrawList();

    // Like pill  ── thumb-up icon  |  count ────────────────────
    {
        ImVec2 cs=TS("24K");
        float pillW=padLR+iconR*2.f+6.f+cs.x+padLR;
        float divX;
        ImGui::SetCursorScreenPos({x,by});
        ImGui::InvisibleButton("##like",{pillW,btnH});
        bool hov=ImGui::IsItemHovered();
        ImU32 bg=hov?C_ACCENT_SOFT:COL32(0,0,0,0);
        wdl->AddRectFilled({x,by},{x+pillW,by+btnH},bg,8.f);
        wdl->AddRect({x,by},{x+pillW,by+btnH},hov?C_ACCENT:C_ACCENT_LINE,8.f,0,1.f);
        float iconCX=x+padLR+iconR;
        IconThumbUp(wdl,{iconCX,cy},iconR,C_ACCENT);
        divX=x+padLR+iconR*2.f+6.f;
        wdl->AddLine({divX,by+6.f},{divX,by+btnH-6.f},C_ACCENT_LINE,1.f);
        Txt(wdl,{divX+4.f,cy-cs.y*.5f},C_ACCENT,"24K");
        x+=pillW+gap;
    }

    // Dislike pill ─────────────────────────────────────────────
    {
        const char* lbl="Dislike";
        ImVec2 ls=TS(lbl);
        float pillW=padLR+iconR*2.f+6.f+ls.x+padLR;
        ImGui::SetCursorScreenPos({x,by}); ImGui::InvisibleButton("##dis",{pillW,btnH});
        bool hov=ImGui::IsItemHovered();
        ImU32 bg=hov?COL32(255,255,255,15):COL32(0,0,0,0);
        wdl->AddRectFilled({x,by},{x+pillW,by+btnH},bg,8.f);
        wdl->AddRect({x,by},{x+pillW,by+btnH},C_BORDER,8.f,0,1.f);
        IconThumbDown(wdl,{x+padLR+iconR,cy},iconR,hov?C_ERROR:C_TEXT_MUTED);
        Txt(wdl,{x+padLR+iconR*2.f+6.f,cy-ls.y*.5f},hov?C_TEXT:C_TEXT_MUTED,lbl);
        x+=pillW+gap;
    }

    wdl->AddLine({x+2.f,by+6.f},{x+2.f,by+btnH-6.f},C_BORDER,1.f); x+=8.f;

    // Share pill ───────────────────────────────────────────────
    {
        const char* lbl="Share";
        ImVec2 ls=TS(lbl);
        float pillW=padLR+iconR*2.f+6.f+ls.x+padLR;
        ImGui::SetCursorScreenPos({x,by}); ImGui::InvisibleButton("##shr",{pillW,btnH});
        bool hov=ImGui::IsItemHovered();
        ImU32 bg=hov?COL32(255,255,255,15):COL32(0,0,0,0);
        wdl->AddRectFilled({x,by},{x+pillW,by+btnH},bg,8.f);
        wdl->AddRect({x,by},{x+pillW,by+btnH},C_BORDER,8.f,0,1.f);
        IconShare(wdl,{x+padLR+iconR,cy},iconR,hov?C_TEXT:C_TEXT_MUTED);
        Txt(wdl,{x+padLR+iconR*2.f+6.f,cy-ls.y*.5f},hov?C_TEXT:C_TEXT_MUTED,lbl);
        x+=pillW+gap;
    }

    // Download pill ────────────────────────────────────────────
    {
        const char* lbl="Download";
        ImVec2 ls=TS(lbl);
        float pillW=padLR+iconR*2.f+6.f+ls.x+padLR;
        ImGui::SetCursorScreenPos({x,by}); ImGui::InvisibleButton("##dl",{pillW,btnH});
        bool hov=ImGui::IsItemHovered();
        ImU32 bg=hov?COL32(255,255,255,15):COL32(0,0,0,0);
        wdl->AddRectFilled({x,by},{x+pillW,by+btnH},bg,8.f);
        wdl->AddRect({x,by},{x+pillW,by+btnH},C_BORDER,8.f,0,1.f);
        IconDownload(wdl,{x+padLR+iconR,cy},iconR,hov?C_TEXT:C_TEXT_MUTED);
        Txt(wdl,{x+padLR+iconR*2.f+6.f,cy-ls.y*.5f},hov?C_TEXT:C_TEXT_MUTED,lbl);
        x+=pillW+gap;
    }

    // More (…) pill ────────────────────────────────────────────
    {
        float pillW=btnH;
        ImGui::SetCursorScreenPos({x,by}); ImGui::InvisibleButton("##more",{pillW,btnH});
        bool hov=ImGui::IsItemHovered();
        ImU32 bg=hov?COL32(255,255,255,15):COL32(0,0,0,0);
        wdl->AddRectFilled({x,by},{x+pillW,by+btnH},bg,8.f);
        wdl->AddRect({x,by},{x+pillW,by+btnH},C_BORDER,8.f,0,1.f);
        IconDots(wdl,{x+pillW*.5f,cy},5.f,hov?C_TEXT:C_TEXT_MUTED);
        x+=pillW+gap;
    }

    // Views + date (right-aligned) ─────────────────────────────
    const char* meta="1.78 views \xe2\x80\xa2 Jul 28, 1987";
    ImVec2 ms=TS(meta);
    Txt(wdl,{pos.x+w-ms.x-10.f,cy-ms.y*.5f},C_TEXT_FAINT,meta);
}

// ─── video area ──────────────────────────────────────────────
static void DrawVideoArea(ImDrawList* dl,ImVec2 pos,float w,float h)
{
    RectFill(dl,pos,{w,h},C_BLACK);

    // Subtle gradient overlay at bottom (for controls legibility)
    dl->AddRectFilledMultiColor(
        {pos.x, pos.y+h*0.65f},
        {pos.x+w, pos.y+h},
        IM_COL32(0,0,0,0), IM_COL32(0,0,0,0),
        IM_COL32(0,0,0,140), IM_COL32(0,0,0,140));

    // Center play indicator (faint)
    float cr=22.f;
    ImVec2 cc={pos.x+w*.5f,pos.y+h*.5f};
    dl->AddCircleFilled(cc,cr,COL32(0,0,0,80),24);
    dl->AddCircle(cc,cr,COL32(255,255,255,40),24,1.5f);
    IconPlay(dl,cc,9.f,COL32(255,255,255,100));
}

// ─── sidebar: related videos ─────────────────────────────────
static void DrawSidebar(ImDrawList* dl,ImVec2 pos,float w,float h)
{
    RectFill(dl,pos,{w,h},C_BG);
    dl->PushClipRect(pos,{pos.x+w,pos.y+h},true);

    const float thumbH=80.f, thumbW=w*0.44f;
    const float cardH=thumbH+2.f, gap=4.f;
    float y=pos.y-g_sideScroll;
    float totalH=(cardH+gap)*g_relatedCount+gap;

    for(int i=0;i<g_relatedCount;i++){
        const RelItem& it=g_related[i];
        float cardY=y;
        if(cardY+cardH>pos.y && cardY<pos.y+h){
            RectFill(dl,{pos.x+4.f,cardY},{w-8.f,cardH},C_SURFACE,4.f);

            // Thumbnail gradient placeholder
            float tx=pos.x+8.f,ty=cardY+1.f;
            RectFill(dl,{tx,ty},{thumbW,thumbH},it.grad,3.f);
            dl->AddRectFilledMultiColor({tx,ty+thumbH*.5f},{tx+thumbW,ty+thumbH},
                IM_COL32(0,0,0,0),IM_COL32(0,0,0,0),
                IM_COL32(0,0,0,120),IM_COL32(0,0,0,120));
            // Duration badge
            ImVec2 ds=TS(it.dur);
            float dx=tx+thumbW-ds.x-5.f, dy=ty+thumbH-ds.y-3.f;
            RectFill(dl,{dx-2.f,dy-1.f},{ds.x+4.f,ds.y+2.f},COL32(0,0,0,160),2.f);
            Txt(dl,{dx,dy},C_TEXT,it.dur);

            // Text info
            float ix=tx+thumbW+6.f, iw=w-thumbW-18.f;
            dl->PushClipRect({ix,cardY},{ix+iw,cardY+cardH},true);
            Txt(dl,{ix,cardY+4.f},C_TEXT,it.title);
            Txt(dl,{ix,cardY+18.f},C_TEXT_MUTED,it.channel);
            Txt(dl,{ix,cardY+30.f},C_TEXT_FAINT,it.views);
            dl->PopClipRect();
        }
        y+=cardH+gap;
    }

    // Scroll handle
    if(totalH>h){
        float trackH=h, thumbFrac=h/totalH;
        float thumbSz=trackH*thumbFrac;
        float scrollFrac=g_sideScroll/(totalH-h);
        float thumbY=pos.y+scrollFrac*(trackH-thumbSz);
        dl->AddRectFilled({pos.x+w-4.f,thumbY},{pos.x+w-1.f,thumbY+thumbSz},
            C_BORDER_STR,2.f);
    }

    dl->PopClipRect();

    // Scroll input (mouse wheel when hovering sidebar)
    ImVec2 mp=ImGui::GetIO().MousePos;
    if(mp.x>=pos.x&&mp.x<=pos.x+w&&mp.y>=pos.y&&mp.y<=pos.y+h){
        g_sideScroll-=ImGui::GetIO().MouseWheel*30.f;
        float maxScroll=totalH-h; if(maxScroll<0)maxScroll=0;
        if(g_sideScroll<0)g_sideScroll=0;
        if(g_sideScroll>maxScroll)g_sideScroll=maxScroll;
    }
}

// ─── subscribe button ─────────────────────────────────────────
static void DrawSubscribeBtn(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h=32.f;
    ImU32 bg = g_subscribed ? C_SURFACE3 : C_ACCENT;
    ImU32 tc = g_subscribed ? C_TEXT_MUTED : C_BG;
    const char* lbl = g_subscribed ? "Subscribed" : "Subscribe";
    ImVec2 ts=TS(lbl);
    RectFill(dl,pos,{w,h},bg,5.f);
    ImGui::SetCursorScreenPos(pos);
    if(ImGui::InvisibleButton("##sub",{w,h})) g_subscribed=!g_subscribed;
    Txt(dl,{pos.x+(w-ts.x)*.5f,pos.y+(h-ts.y)*.5f},tc,lbl);
}

// ─── description panel ───────────────────────────────────────
static void DrawDescription(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h=110.f;
    RectFill(dl,pos,{w,h},C_SURFACE,5.f);
    Rect(dl,pos,{w,h},C_BORDER,5.f);
    dl->PushClipRect(pos,{pos.x+w,pos.y+h},true);
    float y=pos.y+8.f;
    const char* title="Rick Astley \xe2\x80\x94 Never Gonna Give You Up (Official Music Video) [4K UHD]";
    Txt(dl,{pos.x+8.f,y},C_TEXT,title); y+=16.f;
    Txt(dl,{pos.x+8.f,y},C_TEXT_MUTED,"Rick Astley"); y+=14.f;
    Txt(dl,{pos.x+8.f,y},C_TEXT_FAINT,"1.78 views \xe2\x80\xa2 Jul 28, 1987"); y+=18.f;
    const char* desc="The official music video for \xe2\x80\x9cNever Gonna Give You Up\xe2\x80\x9d by Rick Astley from the debut album "
                     "\xe2\x80\x98Whenever You Need Somebody\xe2\x80\x99 \xe2\x80\x94 deluxe 2022 remaster. \xe2\x80\xa2 Remastered in stunning 4K UHD. "
                     "Listen on Spotify, Apple Music & more.";
    dl->AddText(g_font13,13.f,{pos.x+8.f,y},C_TEXT_MUTED,desc,NULL);
    dl->PopClipRect();
}

// ─── autoplay toggle ─────────────────────────────────────────
static bool g_autoplay=true;
static void DrawAutoplay(ImDrawList* dl,ImVec2 pos,float w)
{
    const float h=30.f;
    const char* lbl="Autoplay";
    ImVec2 ts=TS(lbl);
    Txt(dl,{pos.x,pos.y+(h-ts.y)*.5f},C_TEXT_MUTED,lbl);

    // Toggle knob (right-aligned)
    const float kw=34.f,kh=18.f;
    float kx=pos.x+w-kw, ky=pos.y+(h-kh)*.5f;
    ImU32 trackC=g_autoplay?C_ACCENT:C_SURFACE3;
    RectFill(dl,{kx,ky},{kw,kh},trackC,kh*.5f);
    float cx=g_autoplay?(kx+kw-kh*.5f-2.f):(kx+kh*.5f+2.f);
    dl->AddCircleFilled({cx,ky+kh*.5f},kh*.5f-2.f,C_TEXT,12);
    if(g_autoplay){
        float dotX=kx+kh*.5f+2.f, dotY=ky+kh*.5f;
        dl->AddCircleFilled({dotX,dotY},2.5f,COL32(255,255,255,200),8);
    }
    ImGui::SetCursorScreenPos({kx,ky});
    if(ImGui::InvisibleButton("##ap",{kw,kh})) g_autoplay=!g_autoplay;
}

// ─── render frame ────────────────────────────────────────────
static const float TITLEBAR_H   = 38.f;
static const float VIDEO_H      = 300.f;
static const float CTRL_H       = 72.f;
static const float ACTION_H     = 46.f;
static const float DESC_H       = 110.f;
static const float SIDEBAR_W    = 220.f;
static const float AUTOPLAY_H   = 30.f;

static void RenderFrame(ImDrawList* dl,float W,float H)
{
    float mainW = W - SIDEBAR_W;
    float y     = 0.f;

    DrawTitlebar (dl,{0,y},W);           y+=TITLEBAR_H;
    DrawVideoArea(dl,{0,y},mainW,VIDEO_H);
    DrawSidebar  (dl,{mainW,y},SIDEBAR_W,H-TITLEBAR_H);
    y+=VIDEO_H;
    DrawControls (dl,{0,y},mainW);       y+=CTRL_H;
    DrawActionBar(dl,{0,y},mainW);       y+=ACTION_H;

    float descY=y, descW=mainW-120.f;
    DrawDescription(dl,{0,descY},descW);
    DrawSubscribeBtn(dl,{descW+8.f,descY+8.f},104.f);
    y+=DESC_H+8.f;

    DrawAutoplay(dl,{8.f,y},mainW-16.f);
    (void)AUTOPLAY_H;
}

// ─── ImGui window wrapper ─────────────────────────────────────
static void DrawUI(float W,float H)
{
    ImGui::SetNextWindowPos({0,0});
    ImGui::SetNextWindowSize({W,H});
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,{0,0});
    ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize,0);
    ImGui::PushStyleColor(ImGuiCol_WindowBg,U32toV4(C_BG));

    ImGui::Begin("##main",NULL,
        ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoResize|
        ImGuiWindowFlags_NoScrollbar|ImGuiWindowFlags_NoScrollWithMouse|
        ImGuiWindowFlags_NoBringToFrontOnFocus);

    ImDrawList* dl=ImGui::GetWindowDrawList();
    float W2=(float)ImGui::GetWindowWidth();
    float H2=(float)ImGui::GetWindowHeight();
    RenderFrame(dl,W2,H2);

    ImGui::End();
    ImGui::PopStyleColor();
    ImGui::PopStyleVar(2);
}

// ─── WinMain ─────────────────────────────────────────────────
int WINAPI WinMain(HINSTANCE hInst,HINSTANCE,LPSTR,int)
{
    CoInitialize(NULL);

    WNDCLASSEXA wc={sizeof(wc),CS_CLASSDC,WndProc,0,0,hInst,
        LoadIconA(hInst,MAKEINTRESOURCEA(1)),
        NULL,NULL,NULL,"SightlineWnd",NULL};
    RegisterClassExA(&wc);
    g_hwnd=CreateWindowExA(0,"SightlineWnd","Sightline",
        WS_OVERLAPPEDWINDOW,100,100,960,640,NULL,NULL,hInst,NULL);

    if(!CreateDeviceD3D(g_hwnd)){ DestroyWindow(g_hwnd); return 1; }
    ShowWindow(g_hwnd,SW_SHOWDEFAULT);
    UpdateWindow(g_hwnd);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO& io=ImGui::GetIO();
    io.IniFilename=NULL;

    ImGui::StyleColorsDark();
    ImGuiStyle& style=ImGui::GetStyle();
    style.WindowRounding=0; style.FrameRounding=4; style.ScrollbarRounding=4;
    style.FramePadding={4,4}; style.ItemSpacing={6,4};

    ImGui_ImplWin32_Init(g_hwnd);
    ImGui_ImplDX9_Init(g_pd3dDev);

    // ── Font loading ──────────────────────────────────────────
    ImFontConfig cfg;
    cfg.OversampleH=2; cfg.OversampleV=2;
    if(HasElectrolize()){
        cfg.FontDataOwnedByAtlas=false;
        memcpy(cfg.Name,"Electrolize13",sizeof(cfg.Name));
        g_font13=io.Fonts->AddFontFromMemoryTTF(
            const_cast<unsigned char*>(electrolize_regular_ttf),
            (int)electrolize_regular_ttf_len,
            13.f,&cfg,g_glyph_ranges);
        memcpy(cfg.Name,"Electrolize16",sizeof(cfg.Name));
        g_font16=io.Fonts->AddFontFromMemoryTTF(
            const_cast<unsigned char*>(electrolize_regular_ttf),
            (int)electrolize_regular_ttf_len,
            16.f,&cfg,g_glyph_ranges);
    }
    if(!g_font13){
        g_font13=io.Fonts->AddFontDefault();
    }
    if(!g_font16) g_font16=g_font13;
    io.Fonts->Build();
    io.FontDefault=g_font16;

    // ── Logo texture ──────────────────────────────────────────
    if(HasLogo()){
        LoadPNGFromMemory(sightline_logo_png, sightline_logo_png_len,
                          g_pd3dDev, &g_logoTex, &g_logoTexW, &g_logoTexH);
    }

    MSG msg; ZeroMemory(&msg,sizeof(msg));
    while(msg.message!=WM_QUIT){
        if(PeekMessageA(&msg,NULL,0,0,PM_REMOVE)){
            TranslateMessage(&msg); DispatchMessageA(&msg); continue;
        }

        HRESULT hr=g_pd3dDev->TestCooperativeLevel();
        if(hr==D3DERR_DEVICELOST){ Sleep(10); continue; }
        if(hr==D3DERR_DEVICENOTRESET){ ResetDevice(); continue; }

        ImGui_ImplDX9_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();

        float W=(float)ImGui::GetIO().DisplaySize.x;
        float H=(float)ImGui::GetIO().DisplaySize.y;
        DrawUI(W,H);

        ImGui::EndFrame();
        g_pd3dDev->Clear(0,NULL,D3DCLEAR_TARGET|D3DCLEAR_ZBUFFER,
            D3DCOLOR_RGBA(12,16,20,255),1.f,0);
        if(g_pd3dDev->BeginScene()==D3D_OK){
            ImGui::Render();
            ImGui_ImplDX9_RenderDrawData(ImGui::GetDrawData());
            g_pd3dDev->EndScene();
        }
        g_pd3dDev->Present(NULL,NULL,NULL,NULL);
    }

    ImGui_ImplDX9_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();
    CleanupDevice();
    DestroyWindow(g_hwnd);
    UnregisterClassA("SightlineWnd",hInst);
    CoUninitialize();
    return 0;
}
